DROP TABLE `analytics_events`;--> statement-breakpoint
DROP TABLE `bundle_items`;--> statement-breakpoint
DROP TABLE `certifications`;--> statement-breakpoint
DROP TABLE `conversation_messages`;--> statement-breakpoint
DROP TABLE `conversations`;--> statement-breakpoint
DROP TABLE `coupon_usages`;--> statement-breakpoint
DROP TABLE `coupons`;--> statement-breakpoint
DROP TABLE `deliveries`;--> statement-breakpoint
DROP TABLE `detailed_reviews`;--> statement-breakpoint
DROP TABLE `disputes`;--> statement-breakpoint
DROP TABLE `favorite_sellers`;--> statement-breakpoint
DROP TABLE `freelancer_skills`;--> statement-breakpoint
DROP TABLE `order_revisions`;--> statement-breakpoint
DROP TABLE `portfolio_items`;--> statement-breakpoint
DROP TABLE `product_bundles`;--> statement-breakpoint
DROP TABLE `product_licenses`;--> statement-breakpoint
DROP TABLE `product_subscriptions`;--> statement-breakpoint
DROP TABLE `product_tags`;--> statement-breakpoint
DROP TABLE `service_addons`;--> statement-breakpoint
DROP TABLE `service_tags`;--> statement-breakpoint
DROP TABLE `support_tickets`;--> statement-breakpoint
DROP TABLE `tags`;--> statement-breakpoint
DROP TABLE `ticket_replies`;--> statement-breakpoint
DROP TABLE `wishlists`;