-- سوق الخدمات (SERVICE CATEGORIES)
-- ====================================

-- 1. خدمات الكتابة والمحتوى
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الكتابة والمحتوى', 'Writing & Content Services', NULL, 1);
SET @service1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات كتابة المحتوى', 'Content Writing', @service1Id, 1);
SET @service1_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة المقالات', 'كتابة المقالات', @service1_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة المدونات', 'كتابة المدونات', @service1_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة النصوص التسويقية', 'كتابة النصوص التسويقية', @service1_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('أوصاف المنتجات', 'أوصاف المنتجات', @service1_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('النصوص الإعلانية', 'النصوص الإعلانية', @service1_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة السيناريوهات', 'كتابة السيناريوهات', @service1_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة البودكاست', 'كتابة البودكاست', @service1_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة المحتوى التقني', 'كتابة المحتوى التقني', @service1_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة المحتوى الطبي', 'كتابة المحتوى الطبي', @service1_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة المحتوى القانوني', 'كتابة المحتوى القانوني', @service1_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Ghost Writing', 'Ghost Writing', @service1_1Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('كتابة السيرة الذاتية', 'كتابة السيرة الذاتية', @service1_1Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('بحوث وتقارير وتحليلات ودراسات', 'بحوث وتقارير وتحليلات ودراسات', @service1_1Id, 13);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إعداد محتوى ورش عمل ودورات تدريبية', 'إعداد محتوى ورش عمل ودورات تدريبية', @service1_1Id, 14);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('محتويات نصية أخرى', 'محتويات نصية أخرى', @service1_1Id, 15);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات التحرير والترجمة', 'Editing & Translation', @service1Id, 2);
SET @service1_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التحرير اللغوي', 'التحرير اللغوي', @service1_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التدقيق اللغوي', 'التدقيق اللغوي', @service1_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الترجمة العامة', 'الترجمة العامة', @service1_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الترجمة المتخصصة', 'الترجمة المتخصصة', @service1_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الترجمة الفورية', 'الترجمة الفورية', @service1_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التعريب', 'التعريب', @service1_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Transcription', 'Transcription', @service1_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Subtitling', 'Subtitling', @service1_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إعادة الكتابة', 'إعادة الكتابة', @service1_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التلخيص', 'التلخيص', @service1_2Id, 10);

-- 2. خدمات التصميم والإبداع
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات التصميم والإبداع', 'Design & Creative Services', NULL, 2);
SET @service2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التصميم الجرافيكي', 'Graphic Design', @service2Id, 1);
SET @service2_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الشعارات', 'تصميم الشعارات', @service2_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الهوية البصرية', 'الهوية البصرية', @service2_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم البوسترات', 'تصميم البوسترات', @service2_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم البروشورات', 'تصميم البروشورات', @service2_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الكتب', 'تصميم الكتب', @service2_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الأغلفة', 'تصميم الأغلفة', @service2_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم البطاقات', 'تصميم البطاقات', @service2_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم التغليف', 'تصميم التغليف', @service2_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الإعلانات', 'تصميم الإعلانات', @service2_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم السوشيال ميديا', 'تصميم السوشيال ميديا', @service2_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم البانرات', 'تصميم البانرات', @service2_1Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الرسم الرقمي', 'الرسم الرقمي', @service2_1Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تنقيح وتعديل الصور', 'تنقيح وتعديل الصور', @service2_1Id, 13);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التصميم والطباعة', 'Design & Printing', @service2Id, 2);
SET @service2_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم التيشيرتات', 'تصاميم التيشيرتات', @service2_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم الأكواب', 'تصاميم الأكواب', @service2_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم الحقائب', 'تصاميم الحقائب', @service2_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم البوسترات', 'تصاميم البوسترات', @service2_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم الملصقات', 'تصاميم الملصقات', @service2_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم القبعات', 'تصاميم القبعات', @service2_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم الوسائد', 'تصاميم الوسائد', @service2_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم الهواتف', 'تصاميم الهواتف', @service2_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم اللوحات', 'تصاميم اللوحات', @service2_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم البطاقات وبطاقات الأعمال', 'تصاميم البطاقات وبطاقات الأعمال', @service2_2Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم دعوات وبطاقات التهنئة', 'تصاميم دعوات وبطاقات التهنئة', @service2_2Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصاميم شهادات', 'تصاميم شهادات', @service2_2Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم المواقع والتطبيقات', 'Web & App Design', @service2Id, 3);
SET @service2_3Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم UI', 'تصميم UI', @service2_3Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم UX', 'تصميم UX', @service2_3Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم المواقع', 'تصميم المواقع', @service2_3Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم التطبيقات', 'تصميم التطبيقات', @service2_3Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم Dashboard', 'تصميم Dashboard', @service2_3Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Wireframing', 'Wireframing', @service2_3Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Prototyping', 'Prototyping', @service2_3Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الأيقونات', 'تصميم الأيقونات', @service2_3Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم التفاعل', 'تصميم التفاعل', @service2_3Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصميم الاستجابة', 'تصميم الاستجابة', @service2_3Id, 10);

-- 3. خدمات الصوت والفيديو
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الصوت والفيديو', 'Audio & Video Services', NULL, 3);
SET @service3Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الخدمات الصوتية', 'Audio Services', @service3Id, 1);
SET @service3_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التعليق الصوتي', 'التعليق الصوتي', @service3_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إنتاج البودكاست', 'إنتاج البودكاست', @service3_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تأليف الموسيقى', 'تأليف الموسيقى', @service3_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('المؤثرات الصوتية', 'المؤثرات الصوتية', @service3_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الميكساج والماسترنج', 'الميكساج والماسترنج', @service3_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تسجيل وتأليف الأغاني', 'تسجيل وتأليف الأغاني', @service3_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الإنتاج الموسيقي', 'الإنتاج الموسيقي', @service3_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحرير الصوت', 'تحرير الصوت', @service3_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('ترميم الصوت', 'ترميم الصوت', @service3_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Foley Art', 'Foley Art', @service3_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الفيديو', 'Video Services', @service3Id, 2);
SET @service3_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إنتاج الفيديو', 'إنتاج الفيديو', @service3_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصوير الفعاليات والمناسبات', 'تصوير الفعاليات والمناسبات', @service3_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصوير المنتجات', 'تصوير المنتجات', @service3_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('المونتاج', 'المونتاج', @service3_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الموشن جرافيك', 'الموشن جرافيك', @service3_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الرسوم المتحركة 2D', 'الرسوم المتحركة 2D', @service3_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الرسوم المتحركة 3D', 'الرسوم المتحركة 3D', @service3_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('المؤثرات البصرية VFX', 'المؤثرات البصرية VFX', @service3_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تصحيح الألوان', 'تصحيح الألوان', @service3_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('البث المباشر', 'البث المباشر', @service3_2Id, 10);

-- 4. خدمات البرمجة والتطوير
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات البرمجة والتطوير', 'Programming & Development', NULL, 4);
SET @service4Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير المواقع الكاملة', 'Full Website Development', @service4Id, 1);
SET @service4_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Frontend', 'تطوير Frontend', @service4_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Backend', 'تطوير Backend', @service4_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Full Stack Development', 'Full Stack Development', @service4_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير WordPress', 'تطوير WordPress', @service4_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Shopify', 'تطوير Shopify', @service4_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Laravel', 'تطوير Laravel', @service4_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير React', 'تطوير React', @service4_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Vue', 'تطوير Vue', @service4_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Angular', 'تطوير Angular', @service4_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير API', 'تطوير API', @service4_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير CMS', 'تطوير CMS', @service4_1Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('صيانة المواقع ودعم فني', 'صيانة المواقع ودعم فني', @service4_1Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تخصيص  السكربتات والبرمجيات والمكونات الإضافية', 'تخصيص  السكربتات والبرمجيات والمكونات الإضافية', @service4_1Id, 13);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('حلول مؤسسية متخصصة', 'حلول مؤسسية متخصصة', @service4_1Id, 14);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('اختبار البرمجيات (Testing).', 'اختبار البرمجيات (Testing).', @service4_1Id, 15);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تكامل البرمجي (System Integration)', 'تكامل البرمجي (System Integration)', @service4_1Id, 16);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير التطبيقات الكاملة', 'Full App Development', @service4Id, 2);
SET @service4_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير iOS', 'تطوير iOS', @service4_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Android', 'تطوير Android', @service4_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Cross-Platform', 'تطوير Cross-Platform', @service4_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Desktop Apps', 'تطوير Desktop Apps', @service4_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير PWA', 'تطوير PWA', @service4_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير الألعاب', 'تطوير الألعاب', @service4_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير VR/AR', 'تطوير VR/AR', @service4_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير IoT', 'تطوير IoT', @service4_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Blockchain', 'تطوير Blockchain', @service4_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير AI/ML', 'تطوير AI/ML', @service4_2Id, 10);

-- 5. التسويق الرقمي والأعمال
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التسويق الرقمي والأعمال', 'Digital Marketing & Business', NULL, 5);
SET @service5Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات التسويق الرقمي', 'Digital Marketing', @service5Id, 1);
SET @service5_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحسين محركات البحث SEO', 'تحسين محركات البحث SEO', @service5_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التسويق بالمحتوى', 'التسويق بالمحتوى', @service5_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة السوشيال ميديا', 'إدارة السوشيال ميديا', @service5_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الإعلانات المدفوعة PPC', 'الإعلانات المدفوعة PPC', @service5_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التسويق بالبريد الإلكتروني', 'التسويق بالبريد الإلكتروني', @service5_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التسويق بالعمولة', 'التسويق بالعمولة', @service5_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التسويق بالمؤثرين', 'التسويق بالمؤثرين', @service5_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحليل البيانات', 'تحليل البيانات', @service5_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استراتيجيات التسويق', 'استراتيجيات التسويق', @service5_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحسين معدل التحويل CRO', 'تحسين معدل التحويل CRO', @service5_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Growth Hacking', 'Growth Hacking', @service5_1Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Marketing Automation', 'Marketing Automation', @service5_1Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الاستشارات والخدمات المهنية', 'Consulting Services', @service5Id, 2);
SET @service5_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات الأعمال', 'استشارات الأعمال', @service5_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات التسويق', 'استشارات التسويق', @service5_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات مالية', 'استشارات مالية', @service5_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات تقنية وبرمجية', 'استشارات تقنية وبرمجية', @service5_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات الموارد البشرية', 'استشارات الموارد البشرية', @service5_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات قانونية', 'استشارات قانونية', @service5_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات الإدارة', 'استشارات الإدارة', @service5_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('دراسات الجدوى', 'دراسات الجدوى', @service5_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('أبحاث السوق', 'أبحاث السوق', @service5_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تخطيط الأعمال', 'تخطيط الأعمال', @service5_2Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة المشاريع', 'إدارة المشاريع', @service5_2Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Virtual Assistant', 'Virtual Assistant', @service5_2Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات توجيه وإرشاد نفسي وذاتي ووعي وتطوير ذاتي', 'استشارات توجيه وإرشاد نفسي وذاتي ووعي وتطوير ذاتي', @service5_2Id, 13);

-- 6. التعليم والتدريب
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التعليم والتدريب', 'Education & Training', NULL, 6);
SET @service6Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التدريس والتعليم عبر الإنترنت', 'Online Teaching', @service6Id, 1);
SET @service6_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التدريس الخصوصي', 'التدريس الخصوصي', @service6_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعليم اللغات', 'تعليم اللغات', @service6_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعليم البرمجة', 'تعليم البرمجة', @service6_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعليم الموسيقى', 'تعليم الموسيقى', @service6_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعليم الفنون', 'تعليم الفنون', @service6_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التعليم الأكاديمي', 'التعليم الأكاديمي', @service6_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعليم المهارات', 'تعليم المهارات', @service6_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحضير الامتحانات', 'تحضير الامتحانات', @service6_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('IELTS/TOEFL', 'IELTS/TOEFL', @service6_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('SAT/GRE', 'SAT/GRE', @service6_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('التدريب والتطوير المهني', 'Professional Training', @service6Id, 2);
SET @service6_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Life Coaching', 'Life Coaching', @service6_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Business Coaching', 'Business Coaching', @service6_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Career Coaching', 'Career Coaching', @service6_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Executive Coaching', 'Executive Coaching', @service6_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Leadership Training', 'Leadership Training', @service6_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Soft Skills Training', 'Soft Skills Training', @service6_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Technical Training', 'Technical Training', @service6_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Sales Training', 'Sales Training', @service6_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Customer Service Training', 'Customer Service Training', @service6_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Team Building', 'Team Building', @service6_2Id, 10);

-- 7. الخدمات المتخصصة
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الخدمات المتخصصة', 'Specialized Services', NULL, 7);
SET @service7Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات البيانات والتحليل', 'Data & Analytics', @service7Id, 1);
SET @service7_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تحليل البيانات', 'تحليل البيانات', @service7_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('علم البيانات', 'علم البيانات', @service7_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تعلم الآلة', 'تعلم الآلة', @service7_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الذكاء الاصطناعي', 'الذكاء الاصطناعي', @service7_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Business Intelligence', 'Business Intelligence', @service7_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Data Visualization', 'Data Visualization', @service7_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Big Data', 'Big Data', @service7_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Data Mining', 'Data Mining', @service7_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Predictive Analytics', 'Predictive Analytics', @service7_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Statistical Analysis', 'Statistical Analysis', @service7_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الأمن السيبراني', 'Cybersecurity', @service7Id, 2);
SET @service7_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('اختبار الاختراق', 'اختبار الاختراق', @service7_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تقييم الثغرات', 'تقييم الثغرات', @service7_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات الأمن', 'استشارات الأمن', @service7_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Incident Response', 'Incident Response', @service7_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Security Audits', 'Security Audits', @service7_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Compliance', 'Compliance', @service7_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Security Training', 'Security Training', @service7_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Forensics', 'Forensics', @service7_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('SOC Services', 'SOC Services', @service7_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Risk Assessment', 'Risk Assessment', @service7_2Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات العمل الحر الأخرى', 'Other Freelance Services', @service7Id, 3);
SET @service7_3Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة المتاجر الإلكترونية', 'إدارة المتاجر الإلكترونية', @service7_3Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمة العملاء عن بعد', 'خدمة العملاء عن بعد', @service7_3Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدخال البيانات', 'إدخال البيانات', @service7_3Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('البحث على الإنترنت', 'البحث على الإنترنت', @service7_3Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('النسخ الطبي', 'النسخ الطبي', @service7_3Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('المحاسبة عن بعد', 'المحاسبة عن بعد', @service7_3Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة حسابات التواصل', 'إدارة حسابات التواصل', @service7_3Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Community Management', 'Community Management', @service7_3Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Content Moderation', 'Content Moderation', @service7_3Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Online Reputation Management', 'Online Reputation Management', @service7_3Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة حسابات التداول اليومي', 'إدارة حسابات التداول اليومي', @service7_3Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('إدارة حسابات التسويق بالعمولة', 'إدارة حسابات التسويق بالعمولة', @service7_3Id, 12);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الربط بين الشركات والفريلانسرز', 'خدمات الربط بين الشركات والفريلانسرز', @service7_3Id, 13);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('خدمات الذكاء الاصطناعي والوكلاء والأتمتة', 'AI & Automation', @service7Id, 4);
SET @service7_4Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('تطوير Chatbots', 'تطوير Chatbots', @service7_4Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Virtual AI Assistants', 'Virtual AI Assistants', @service7_4Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Content Generation', 'AI Content Generation', @service7_4Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Voice Services', 'AI Voice Services', @service7_4Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Image Generation', 'AI Image Generation', @service7_4Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Video Generation', 'AI Video Generation', @service7_4Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Process Automation', 'Process Automation', @service7_4Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Workflow Automation', 'Workflow Automation', @service7_4Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('RPA Services', 'RPA Services', @service7_4Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Training Services', 'AI Training Services', @service7_4Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('AI Integration Services', 'AI Integration Services', @service7_4Id, 11);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('No-code/Low-code Development', 'No-code/Low-code Development', @service7_4Id, 12);

-- 8. الخدمات الحية والتفاعلية
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الخدمات الحية والتفاعلية', 'Live & Interactive Services', NULL, 8);
SET @service8Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الفعاليات والورش الحية', 'Live Events & Workshops', @service8Id, 1);
SET @service8_1Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('ورش العمل الحية', 'ورش العمل الحية', @service8_1Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الندوات الحية', 'الندوات الحية', @service8_1Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('المؤتمرات الافتراضية', 'المؤتمرات الافتراضية', @service8_1Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الدورات الحية', 'الدورات الحية', @service8_1Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('جلسات Q&A', 'جلسات Q&A', @service8_1Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Masterclasses', 'Masterclasses', @service8_1Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Panel Discussions', 'Panel Discussions', @service8_1Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Virtual Summits', 'Virtual Summits', @service8_1Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Networking Events', 'Networking Events', @service8_1Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Virtual Trade Shows', 'Virtual Trade Shows', @service8_1Id, 10);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('الاستشارات الشخصية', 'Personal Consulting', @service8Id, 2);
SET @service8_2Id = LAST_INSERT_ID();
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('استشارات 1-on-1', 'استشارات 1-on-1', @service8_2Id, 1);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Group Coaching', 'Group Coaching', @service8_2Id, 2);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Mentoring', 'Mentoring', @service8_2Id, 3);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Strategy Sessions', 'Strategy Sessions', @service8_2Id, 4);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Brainstorming Sessions', 'Brainstorming Sessions', @service8_2Id, 5);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Review Sessions', 'Review Sessions', @service8_2Id, 6);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Feedback Sessions', 'Feedback Sessions', @service8_2Id, 7);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Planning Sessions', 'Planning Sessions', @service8_2Id, 8);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Accountability Coaching', 'Accountability Coaching', @service8_2Id, 9);
INSERT INTO service_categories (nameAr, nameEn, parentId, `order`) VALUES ('Performance Coaching', 'Performance Coaching', @service8_2Id, 10);


-- سوق فرص العمل (JOB CATEGORIES)
-- ====================================

INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الذكاء الاصطناعي والوكلاء والأتمتة', 'AI & Automation', NULL, 1);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('البرمجة والتطوير وتكنولوجيا المعلومات والتقنية', 'Programming & IT', NULL, 2);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الأعمال والمشاريع والمهام والإدارة', 'Business & Management', NULL, 3);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('المالية والاقتصاد والمحاسبة', 'Finance & Accounting', NULL, 4);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('المبيعات والتسويق', 'Sales & Marketing', NULL, 5);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الكتابة والترجمة والمحتوى', 'Writing & Translation', NULL, 6);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('التصميم والإبداع', 'Design & Creative', NULL, 7);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('إعداد الدراسات والبحوث والتقارير والخطط', 'Research & Reports', NULL, 8);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('التعليم والتدريب', 'Education & Training', NULL, 9);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('القانون', 'Legal', NULL, 10);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الهندسة والعمارة', 'Engineering & Architecture', NULL, 11);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الإدارة والدعم والتشغيل', 'Admin & Support', NULL, 12);
INSERT INTO job_categories (nameAr, nameEn, parentId, `order`) VALUES ('الموارد البشرية والتوظيف', 'HR & Recruitment', NULL, 13);