/**
 * الكتالوج الكامل للتصنيفات من برومبت OSDM — حرفياً دون إسقاط.
 * A: المنتجات الرقمية الجاهزة (Gumroad + Picalica) — أساسي → فرعي → أنواع
 * B: الخدمات الرقمية حسب الطلب (Fiverr + Khamsat) — أساسي → فرعي → أنواع
 * C: فرص العمل الحر (Upwork + Mostaql + Bahr) — المجالات من البرومبت والفروع مصممة وفق المنصات المستنسخة
 */

export type CatalogEntry = {
  ar: string;
  en: string;
  icon?: string;
  descAr?: string;
  descEn?: string;
  children?: CatalogEntry[];
};

// ============================================================
// A — المنتجات الرقمية الجاهزة ذات الدخل السلبي
// ============================================================
export const PRODUCT_CATALOG: CatalogEntry[] = [
  {
    ar: "المحتوى النصي والمكتوب", en: "Written & Text Content", icon: "📝",
    children: [
      {
        ar: "الكتب الإلكترونية", en: "E-Books", icon: "📚",
        children: [
          { ar: "كتب علمية وأكاديمية", en: "Scientific & Academic Books", descAr: "كتب في العلوم الطبيعية، الرياضيات، الفيزياء، الكيمياء، الأحياء", descEn: "Books in natural sciences, mathematics, physics, chemistry, biology" },
          { ar: "كتب أطفال واليافعين", en: "Children & Young Adult Books", descAr: "قصص مصورة، كتب تعليمية، حكايات، كتب تلوين رقمية", descEn: "Picture stories, educational books, tales, digital coloring books" },
          { ar: "كتب تطوير وتنمية الذات", en: "Self-Development Books", descAr: "التحفيز، الإنتاجية، العادات، النجاح، السعادة", descEn: "Motivation, productivity, habits, success, happiness" },
          { ar: "السير الذاتية والمذكرات", en: "Biographies & Memoirs", descAr: "قصص حياة، سير شخصيات مشهورة، مذكرات شخصية", descEn: "Life stories, famous figures biographies, personal memoirs" },
          { ar: "كتب التاريخ", en: "History Books", descAr: "تاريخ عام، تاريخ البلدان، تاريخ الحضارات", descEn: "General history, countries history, civilizations history" },
          { ar: "كتب الجغرافيا", en: "Geography Books", descAr: "أطالس، جغرافيا بشرية، جغرافيا طبيعية", descEn: "Atlases, human geography, physical geography" },
          { ar: "العلوم والعلوم الطبيعية", en: "Science & Natural Sciences", descAr: "فيزياء، كيمياء، رياضيات، أحياء، فلك، جيولوجيا", descEn: "Physics, chemistry, mathematics, biology, astronomy, geology" },
          { ar: "العلوم الاجتماعية", en: "Social Sciences", descAr: "علم نفس، علم اجتماع، اقتصاد سلوكي، سياسة، أنثروبولوجيا", descEn: "Psychology, sociology, behavioral economics, politics, anthropology" },
          { ar: "أعمال واقتصاد", en: "Business & Economics", descAr: "إدارة، تسويق، مالية، ريادة وإدارة أعمال، اقتصاد، محاسبة، تجارة إلكترونية، موارد بشرية", descEn: "Management, marketing, finance, entrepreneurship, economics, accounting, e-commerce, HR" },
          { ar: "دين وفلسفة", en: "Religion & Philosophy", descAr: "كتب دينية، فلسفة دينية، روحانيات", descEn: "Religious books, religious philosophy, spirituality" },
          { ar: "الفنون والحرف", en: "Arts & Crafts", descAr: "رسم، نحت، تصوير، حرف يدوية", descEn: "Drawing, sculpture, photography, handicrafts" },
          { ar: "كتب تعليم الموضة والتجميل وصناعة الحلي والعطور", en: "Fashion, Beauty, Jewelry & Perfume Making Books", descAr: "أزياء، مكياج، مستحضرات تجميل وعناية بالبشرة، عطور، أحجار كريمة ومجوهرات، إكسسوارات", descEn: "Fashion, makeup, cosmetics and skincare, perfumes, gemstones and jewelry, accessories" },
          { ar: "الطبخ والطعام", en: "Cooking & Food", descAr: "وصفات، كتب طبخ، تغذية، حميات", descEn: "Recipes, cookbooks, nutrition, diets" },
          { ar: "الطب والصحة", en: "Medicine & Health", descAr: "صحة عامة، لياقة بدنية، صحة نفسية، طب بديل", descEn: "Public health, fitness, mental health, alternative medicine" },
          { ar: "التقنية والحاسوب", en: "Technology & Computing", descAr: "برمجة، شبكات، أمن معلومات، ذكاء اصطناعي", descEn: "Programming, networks, information security, artificial intelligence" },
          { ar: "السفر والسياحة والترفيه", en: "Travel, Tourism & Entertainment", descAr: "أدلة سياحية، رحلات، ثقافات", descEn: "Travel guides, trips, cultures" },
          { ar: "التعليم والكتب المدرسية", en: "Education & Textbooks", descAr: "مناهج، كتب تعليمية، موارد تعليمية", descEn: "Curricula, educational books, learning resources" },
          { ar: "الرياضة", en: "Sports", descAr: "تدريب رياضي، قواعد اللعب، تاريخ الرياضة", descEn: "Sports training, game rules, sports history" },
          { ar: "القانون", en: "Law", descAr: "قوانين، لوائح، دراسات قانونية", descEn: "Laws, regulations, legal studies" },
          { ar: "البيئة والطبيعة", en: "Environment & Nature", descAr: "علوم بيئية، استدامة، حماية البيئة", descEn: "Environmental sciences, sustainability, environmental protection" },
          { ar: "المراجع", en: "References", descAr: "قواميس، موسوعات، أطالس، معاجم، مخطوطات", descEn: "Dictionaries, encyclopedias, atlases, lexicons, manuscripts" },
          { ar: "الروايات والخيال", en: "Novels & Fiction", descAr: "أدبية، خيال علمي، فانتازيا، رعب، إثارة وتشويق، جريمة، رومانسية، دراما، كوميديا، تاريخية، ديستوبيا يوتوبيا", descEn: "Literary, sci-fi, fantasy, horror, thriller, crime, romance, drama, comedy, historical, dystopia/utopia" },
          { ar: "الأدب الكلاسيكي", en: "Classical Literature", descAr: "أعمال كلاسيكية، أدب عالمي", descEn: "Classical works, world literature" },
          { ar: "القصص القصيرة", en: "Short Stories", descAr: "مجموعات قصصية، قصص قصيرة", descEn: "Story collections, short stories" },
          { ar: "الروايات المصورة", en: "Graphic Novels", descAr: "كوميكس، مانجا، روايات مصورة", descEn: "Comics, manga, graphic novels" },
          { ar: "المسرحيات", en: "Plays", descAr: "نصوص مسرحية، دراما", descEn: "Theatrical scripts, drama" },
          { ar: "الشعر", en: "Poetry", descAr: "دواوين شعرية، قصائد", descEn: "Poetry collections, poems" },
          { ar: "الأساطير والخرافات", en: "Myths & Legends", descAr: "حكايات شعبية، أساطير", descEn: "Folk tales, legends" },
        ],
      },
      {
        ar: "البحوث والدراسات والتقارير والتحليلات", en: "Research, Studies, Reports & Analysis", icon: "🔬",
        children: [
          { ar: "أبحاث السوق", en: "Market Research", descAr: "دراسات السوق، تحليلات الصناعة", descEn: "Market studies, industry analysis" },
          { ar: "تقارير الصناعة", en: "Industry Reports", descAr: "تقارير قطاعية، تحليلات اقتصادية، تحليلات مالية", descEn: "Sector reports, economic analysis, financial analysis" },
          { ar: "دراسات الجدوى", en: "Feasibility Studies", descAr: "دراسات جدوى المشاريع", descEn: "Project feasibility studies" },
          { ar: "أوراق بيضاء", en: "White Papers", descAr: "White Papers، أبحاث تقنية", descEn: "White papers, technical research" },
          { ar: "دراسات حالة", en: "Case Studies", descAr: "Case Studies، قصص نجاح", descEn: "Case studies, success stories" },
          { ar: "تقارير إحصائية", en: "Statistical Reports", descAr: "بيانات وإحصائيات", descEn: "Data and statistics" },
          { ar: "بحوث علمية ودراسات علمية", en: "Scientific Research & Studies", descAr: "جميع أنواع البحوث والدراسات العلمية", descEn: "All types of scientific research and studies" },
        ],
      },
      {
        ar: "القوالب والنماذج النصية", en: "Text Templates & Forms", icon: "📄",
        children: [
          { ar: "قوالب السيرة الذاتية", en: "CV Templates", descAr: "نماذج CV احترافية", descEn: "Professional CV templates" },
          { ar: "قوالب الخطابات الرسمية", en: "Official Letter Templates", descAr: "خطابات عمل، خطابات تقديم، صيغ خطابات مراسلات", descEn: "Business letters, cover letters, correspondence formats" },
          { ar: "قوالب خطط العمل", en: "Business Plan Templates", descAr: "Business Plans", descEn: "Business plans" },
          { ar: "قوالب العقود القانونية", en: "Legal Contract Templates", descAr: "عقود عمل، اتفاقيات", descEn: "Employment contracts, agreements" },
          { ar: "قوالب التسويق", en: "Marketing Templates", descAr: "محتوى تسويقي، منشورات سوشيال ميديا، نصوص إعلانية جاهزة", descEn: "Marketing content, social media posts, ready ad copy" },
          { ar: "قوالب البريد الإلكتروني", en: "Email Templates", descAr: "رسائل تسويقية، نشرات بريدية، صيغ رسمية", descEn: "Marketing emails, newsletters, formal formats" },
          { ar: "قوالب الفواتير", en: "Invoice Templates", descAr: "نماذج فواتير احترافية", descEn: "Professional invoice templates" },
          { ar: "قوالب العروض التقديمية", en: "Presentation Templates", descAr: "PowerPoint، Google Slides", descEn: "PowerPoint, Google Slides" },
          { ar: "قوالب المستندات", en: "Document Templates", descAr: "Word، Google Docs", descEn: "Word, Google Docs" },
          { ar: "قوالب التقارير", en: "Report Templates", descAr: "تقارير أعمال، تقارير أداء", descEn: "Business reports, performance reports" },
        ],
      },
      {
        ar: "المحتوى التعليمي والإعلامي المكتوب", en: "Written Educational & Media Content", icon: "🎓",
        children: [
          { ar: "دورات تدريبية مكتوبة وملفات تعليمية", en: "Written Courses & Educational Files", descAr: "مواد تعليمية نصية", descEn: "Text-based educational materials" },
          { ar: "ملخصات جاهزة", en: "Ready Summaries", descAr: "ملخصات كتب، ملخصات دورات", descEn: "Book summaries, course summaries" },
          { ar: "كتيبات وأدلة تعليمية", en: "Educational Booklets & Guides", descAr: "أدلة استخدام، كتيبات تعليمية", descEn: "User guides, educational booklets" },
          { ar: "كتيبات وأدلة إرشادية", en: "How-to Guides", descAr: "How-to Guides", descEn: "How-to guides" },
          { ar: "مقالات ومدونات ومنشورات", en: "Articles, Blogs & Posts", descAr: "مقالات PLR قابلة لإعادة النشر", descEn: "PLR republishable articles" },
          { ar: "ملفات تعليمية", en: "Educational Files", descAr: "PDF تعليمية", descEn: "Educational PDFs" },
          { ar: "أوراق عمل", en: "Worksheets", descAr: "Worksheets، تمارين", descEn: "Worksheets, exercises" },
          { ar: "اختبارات ومسابقات", en: "Quizzes & Exams", descAr: "Quizzes، امتحانات", descEn: "Quizzes, exams" },
          { ar: "ملفات (برومبتات)", en: "Prompt Files", descAr: "برومبتات جاهزة – هندسة الأوامر", descEn: "Ready prompts – prompt engineering" },
        ],
      },
    ],
  },
  {
    ar: "المحتوى المرئي (البصري)", en: "Visual Content", icon: "🎨",
    children: [
      {
        ar: "قوالب التصميم الجرافيكي", en: "Graphic Design Templates", icon: "🖌️",
        children: [
          { ar: "قوالب Canva", en: "Canva Templates", descAr: "تصاميم جاهزة للتعديل", descEn: "Ready-to-edit designs" },
          { ar: "قوالب Photoshop", en: "Photoshop Templates", descAr: "PSD Files", descEn: "PSD files" },
          { ar: "قوالب Illustrator", en: "Illustrator Templates", descAr: "AI Files", descEn: "AI files" },
          { ar: "قوالب InDesign", en: "InDesign Templates", descAr: "INDD Files", descEn: "INDD files" },
          { ar: "قوالب Figma", en: "Figma Templates", descAr: "تصاميم UI/UX", descEn: "UI/UX designs" },
          { ar: "قوالب Sketch", en: "Sketch Templates", descAr: "تصاميم واجهات", descEn: "Interface designs" },
          { ar: "قوالب After Effects", en: "After Effects Templates", descAr: "مشاريع موشن جرافيك", descEn: "Motion graphics projects" },
          { ar: "قوالب Premiere Pro", en: "Premiere Pro Templates", descAr: "مشاريع فيديو", descEn: "Video projects" },
        ],
      },
      {
        ar: "الصور والرسومات", en: "Photos & Illustrations", icon: "🖼️",
        children: [
          { ar: "صور فوتوغرافية مخزنة", en: "Stock Photos", descAr: "Stock Photos", descEn: "Stock photos" },
          { ar: "رسوم توضيحية", en: "Illustrations", descAr: "Illustrations", descEn: "Illustrations" },
          { ar: "أيقونات", en: "Icon Sets", descAr: "Icons Sets", descEn: "Icon sets" },
          { ar: "شخصيات كرتونية", en: "Characters & Mascots", descAr: "Characters، Mascots", descEn: "Characters, mascots" },
          { ar: "رسومات فنية", en: "Digital Art", descAr: "Digital Art", descEn: "Digital art" },
          { ar: "إنفوجرافيك", en: "Infographics", descAr: "معلومات بصرية", descEn: "Visual information" },
          { ar: "رسوم بيانية", en: "Charts & Graphs", descAr: "Charts، Graphs", descEn: "Charts, graphs" },
          { ar: "خلفيات", en: "Backgrounds & Wallpapers", descAr: "Backgrounds، Wallpapers", descEn: "Backgrounds, wallpapers" },
          { ar: "أنماط", en: "Patterns & Textures", descAr: "Patterns، Textures", descEn: "Patterns, textures" },
          { ar: "ملصقات رقمية", en: "Digital Stickers", descAr: "Digital Stickers", descEn: "Digital stickers" },
          { ar: "صور PNG شفافة", en: "Transparent PNG Images", descAr: "Transparent Images", descEn: "Transparent images" },
          { ar: "صور Vector", en: "Vector Images", descAr: "SVG، EPS Files", descEn: "SVG, EPS files" },
          { ar: "تصاميم ديكورات جاهزة", en: "Ready Decor Designs", descAr: "ديكورات", descEn: "Decorations" },
        ],
      },
      {
        ar: "تصاميم الطباعة", en: "Print Designs", icon: "👕",
        children: [
          { ar: "تصاميم التيشيرتات", en: "T-shirt Designs", descAr: "T-shirt Designs", descEn: "T-shirt designs" },
          { ar: "تصاميم الأكواب", en: "Mug Designs", descAr: "Mug Designs", descEn: "Mug designs" },
          { ar: "تصاميم الحقائب", en: "Bag Designs", descAr: "Bag Designs", descEn: "Bag designs" },
          { ar: "تصاميم البوسترات", en: "Poster Designs", descAr: "Poster Designs", descEn: "Poster designs" },
          { ar: "تصاميم الملصقات", en: "Sticker Designs", descAr: "Sticker Designs", descEn: "Sticker designs" },
          { ar: "تصاميم القبعات", en: "Hat Designs", descAr: "Hat Designs", descEn: "Hat designs" },
          { ar: "تصاميم الوسائد", en: "Pillow Designs", descAr: "Pillow Designs", descEn: "Pillow designs" },
          { ar: "تصاميم الهواتف", en: "Phone Case Designs", descAr: "Phone Case Designs", descEn: "Phone case designs" },
          { ar: "تصاميم اللوحات", en: "Canvas Prints", descAr: "Canvas Prints", descEn: "Canvas prints" },
          { ar: "تصاميم البطاقات وبطاقات الأعمال", en: "Card & Business Card Designs", descAr: "Card Designs", descEn: "Card designs" },
          { ar: "تصاميم دعوات وبطاقات التهنئة", en: "Invitation & Greeting Card Designs", descAr: "دعوات وتهنئة", descEn: "Invitations and greetings" },
          { ar: "تصاميم شهادات", en: "Certificate Designs", descAr: "شهادات", descEn: "Certificates" },
        ],
      },
      {
        ar: "قوالب الأعمال والإنتاجية", en: "Business & Productivity Templates", icon: "📊",
        children: [
          { ar: "قوالب Excel", en: "Excel Templates", descAr: "جداول بيانات، حسابات", descEn: "Spreadsheets, calculations" },
          { ar: "قوالب Google Sheets", en: "Google Sheets Templates", descAr: "جداول إلكترونية", descEn: "Online spreadsheets" },
          { ar: "قوالب Notion", en: "Notion Templates", descAr: "قوالب إنتاجية", descEn: "Productivity templates" },
          { ar: "قوالب Airtable", en: "Airtable Templates", descAr: "قواعد بيانات", descEn: "Databases" },
          { ar: "قوالب Monday", en: "Monday Templates", descAr: "إدارة مشاريع", descEn: "Project management" },
          { ar: "قوالب Trello", en: "Trello Templates", descAr: "بطاقات مهام", descEn: "Task cards" },
          { ar: "قوالب Asana", en: "Asana Templates", descAr: "تنظيم مشاريع", descEn: "Project organization" },
          { ar: "مخططات رقمية", en: "Digital Planners", descAr: "Digital Planners", descEn: "Digital planners" },
          { ar: "قوالب التقويم", en: "Calendar Templates", descAr: "Calendar Templates", descEn: "Calendar templates" },
          { ar: "قوالب الميزانية", en: "Budget Templates", descAr: "Budget Templates", descEn: "Budget templates" },
        ],
      },
      {
        ar: "موارد التصميم", en: "Design Resources", icon: "🧰",
        children: [
          { ar: "خطوط رقمية", en: "Fonts & Typography", descAr: "Fonts، Typography", descEn: "Fonts, typography" },
          { ar: "فُرَش فوتوشوب", en: "Photoshop Brushes", descAr: "Photoshop Brushes", descEn: "Photoshop brushes" },
          { ar: "أدوات تصميم", en: "Design Tools", descAr: "Design Tools", descEn: "Design tools" },
          { ar: "Actions", en: "Photoshop Actions", descAr: "Photoshop Actions", descEn: "Photoshop actions" },
          { ar: "Presets", en: "Lightroom Presets", descAr: "Lightroom Presets", descEn: "Lightroom presets" },
          { ar: "LUTs", en: "Color Grading LUTs", descAr: "Color Grading", descEn: "Color grading" },
          { ar: "Mockups", en: "Product Mockups", descAr: "Product Mockups", descEn: "Product mockups" },
          { ar: "فلاتر وتأثيرات", en: "Filters & Effects", descAr: "Filters، Effects", descEn: "Filters, effects" },
          { ar: "Overlays", en: "Overlays", descAr: "تأثيرات إضافية", descEn: "Additional effects" },
          { ar: "Gradients", en: "Gradients", descAr: "تدرجات لونية", descEn: "Color gradients" },
        ],
      },
    ],
  },
  {
    ar: "المحتوى السمعي (الصوتي)", en: "Audio Content", icon: "🎵",
    children: [
      {
        ar: "الموسيقى والمؤثرات الصوتية", en: "Music & Sound Effects", icon: "🎼",
        children: [
          { ar: "موسيقى خالية من حقوق الملكية", en: "Royalty-Free Music", descAr: "Royalty-Free Music", descEn: "Royalty-free music" },
          { ar: "موسيقى خلفية", en: "Background Music", descAr: "Background Music", descEn: "Background music" },
          { ar: "موسيقى تصويرية", en: "Soundtrack Music", descAr: "Soundtrack Music", descEn: "Soundtrack music" },
          { ar: "مؤثرات صوتية", en: "Sound Effects", descAr: "Sound Effects", descEn: "Sound effects" },
          { ar: "أصوات طبيعية", en: "Nature Sounds", descAr: "Nature Sounds", descEn: "Nature sounds" },
          { ar: "أصوات المدينة", en: "Urban Sounds", descAr: "Urban Sounds", descEn: "Urban sounds" },
          { ar: "Loops موسيقية", en: "Music Loops", descAr: "Music Loops", descEn: "Music loops" },
          { ar: "Beats", en: "Beats", descAr: "إيقاعات موسيقية", descEn: "Musical beats" },
          { ar: "نغمات رنين", en: "Ringtones", descAr: "Ringtones", descEn: "Ringtones" },
          { ar: "تنبيهات صوتية", en: "Alert Sounds", descAr: "Alert Sounds", descEn: "Alert sounds" },
        ],
      },
      {
        ar: "المحتوى الصوتي التعليمي والترفيهي", en: "Educational & Entertainment Audio", icon: "🎧",
        children: [
          { ar: "كتب صوتية", en: "Audiobooks", descAr: "Audiobooks", descEn: "Audiobooks" },
          { ar: "بودكاست مسجل", en: "Recorded Podcasts", descAr: "Recorded Podcasts", descEn: "Recorded podcasts" },
          { ar: "دروس صوتية", en: "Audio Lessons", descAr: "Audio Lessons", descEn: "Audio lessons" },
          { ar: "محاضرات مسجلة", en: "Recorded Lectures", descAr: "Recorded Lectures", descEn: "Recorded lectures" },
          { ar: "قصص وروايات صوتية", en: "Audio Stories", descAr: "Audio Stories", descEn: "Audio stories" },
          { ar: "تأملات موجهة", en: "Guided Meditations", descAr: "Guided Meditations", descEn: "Guided meditations" },
          { ar: "ملفات استرخاء وتأملات", en: "Relaxation Audio", descAr: "Relaxation Audio", descEn: "Relaxation audio" },
          { ar: "ملفات ASMR", en: "ASMR Content", descAr: "ASMR Content", descEn: "ASMR content" },
          { ar: "دورات تدريبية صوتية", en: "Audio Courses", descAr: "Audio Courses", descEn: "Audio courses" },
          { ar: "ندوات مسجلة وموارد تعليمية", en: "Recorded Webinars & Learning Resources", descAr: "Recorded Webinars", descEn: "Recorded webinars" },
          { ar: "أغاني", en: "Songs", descAr: "أغاني", descEn: "Songs" },
        ],
      },
    ],
  },
  {
    ar: "المحتوى المرئي المتحرك (الفيديو)", en: "Video Content", icon: "🎬",
    children: [
      {
        ar: "لقطات ومقاطع الفيديو", en: "Video Footage & Clips", icon: "📹",
        children: [
          { ar: "لقطات فيديو مخزنة", en: "Stock Footage", descAr: "Stock Footage", descEn: "Stock footage" },
          { ar: "مقاطع فيديو قصيرة", en: "Short Videos", descAr: "Short Videos", descEn: "Short videos" },
          { ar: "مقاطع فيديو طويلة", en: "Long Videos", descAr: "Long Videos", descEn: "Long videos" },
          { ar: "فيديو خلفيات متحركة", en: "Video Backgrounds", descAr: "Video Backgrounds", descEn: "Video backgrounds" },
          { ar: "فلاتر تأثيرات فيديو جاهزة", en: "Ready Video Effect Filters", descAr: "فلاتر فيديو", descEn: "Video filters" },
          { ar: "مقاطع Drone", en: "Aerial Drone Footage", descAr: "Aerial Footage", descEn: "Aerial footage" },
          { ar: "مقاطع Time-lapse", en: "Time-lapse Clips", descAr: "فيديو مسرّع", descEn: "Time-lapse video" },
          { ar: "مقاطع Slow Motion", en: "Slow Motion Clips", descAr: "فيديو بطيء", descEn: "Slow motion video" },
          { ar: "مقاطع 360 درجة", en: "360° Videos", descAr: "360° Videos", descEn: "360° videos" },
          { ar: "مقاطع VR", en: "Virtual Reality Videos", descAr: "Virtual Reality Videos", descEn: "Virtual reality videos" },
          { ar: "مقاطع Green Screen", en: "Green Screen Videos", descAr: "Chroma Key Videos", descEn: "Chroma key videos" },
        ],
      },
      {
        ar: "قوالب الفيديو والموشن جرافيك", en: "Video & Motion Graphics Templates", icon: "✨",
        children: [
          { ar: "قوالب المقدمات", en: "Intro Templates", descAr: "Intro Templates", descEn: "Intro templates" },
          { ar: "قوالب الخاتمات", en: "Outro Templates", descAr: "Outro Templates", descEn: "Outro templates" },
          { ar: "قوالب العناوين", en: "Title Templates", descAr: "Title Templates", descEn: "Title templates" },
          { ar: "قوالب الانتقالات", en: "Transition Templates", descAr: "Transition Templates", descEn: "Transition templates" },
          { ar: "قوالب Lower Thirds", en: "Lower Thirds Templates", descAr: "شريط معلومات", descEn: "Information bar" },
          { ar: "قوالب الإعلانات", en: "Ad Templates", descAr: "Ad Templates", descEn: "Ad templates" },
          { ar: "قوالب السوشيال ميديا", en: "Social Media Video Templates", descAr: "Social Media Videos", descEn: "Social media videos" },
          { ar: "رسوم متحركة جاهزة", en: "Ready Motion Graphics", descAr: "Motion Graphics", descEn: "Motion graphics" },
          { ar: "قوالب الشرح", en: "Explainer Video Templates", descAr: "Explainer Videos", descEn: "Explainer videos" },
          { ar: "قوالب العروض المتحركة", en: "Animated Presentation Templates", descAr: "Presentation Videos", descEn: "Presentation videos" },
        ],
      },
      {
        ar: "المحتوى التعليمي المرئي", en: "Visual Educational Content", icon: "📖",
        children: [
          { ar: "دورات فيديو مسجلة", en: "Video Courses", descAr: "Video Courses", descEn: "Video courses" },
          { ar: "شروحات تعليمية", en: "Tutorial Videos", descAr: "Tutorial Videos", descEn: "Tutorial videos" },
          { ar: "محاضرات مسجلة", en: "Recorded Lectures", descAr: "Recorded Lectures", descEn: "Recorded lectures" },
          { ar: "ورش عمل مسجلة", en: "Recorded Workshops", descAr: "Recorded Workshops", descEn: "Recorded workshops" },
          { ar: "ندوات مسجلة", en: "Recorded Seminars", descAr: "Recorded Seminars", descEn: "Recorded seminars" },
          { ar: "دروس مسجلة", en: "Recorded Lessons", descAr: "Recorded Lessons", descEn: "Recorded lessons" },
          { ar: "أفلام وثائقية", en: "Documentaries", descAr: "Documentaries", descEn: "Documentaries" },
          { ar: "فيديوهات How-to", en: "How-to Videos", descAr: "إرشادات مرئية", descEn: "Visual guides" },
          { ar: "مراجعات منتجات", en: "Product Reviews", descAr: "Product Reviews", descEn: "Product reviews" },
          { ar: "دليل استخدام مرئي", en: "Video Manuals", descAr: "Video Manuals", descEn: "Video manuals" },
        ],
      },
    ],
  },
  {
    ar: "المحتوى التفاعلي والرقمي", en: "Interactive & Digital Content", icon: "🎮",
    children: [
      {
        ar: "الألعاب والتطبيقات الجاهزة", en: "Ready Games & Apps", icon: "🕹️",
        children: [
          { ar: "ألعاب بسيطة", en: "Casual Games", descAr: "Casual Games", descEn: "Casual games" },
          { ar: "ألعاب تعليمية", en: "Educational Games", descAr: "Educational Games", descEn: "Educational games" },
          { ar: "ألعاب الألغاز", en: "Puzzle Games", descAr: "Puzzle Games", descEn: "Puzzle games" },
          { ar: "تطبيقات أدوات", en: "Utility Apps", descAr: "Utility Apps", descEn: "Utility apps" },
          { ar: "تطبيقات إنتاجية", en: "Productivity Apps", descAr: "Productivity Apps", descEn: "Productivity apps" },
          { ar: "تطبيقات تعليمية", en: "Learning Apps", descAr: "Learning Apps", descEn: "Learning apps" },
          { ar: "Game Assets", en: "Game Assets", descAr: "موارد ألعاب", descEn: "Game resources" },
          { ar: "Unity Assets", en: "Unity Assets", descAr: "موارد Unity", descEn: "Unity resources" },
          { ar: "Unreal Assets", en: "Unreal Assets", descAr: "موارد Unreal", descEn: "Unreal resources" },
          { ar: "Game Templates", en: "Game Templates", descAr: "قوالب ألعاب", descEn: "Game templates" },
        ],
      },
      {
        ar: "المحتويات التفاعلية الأخرى", en: "Other Interactive Content", icon: "🧩",
        children: [
          { ar: "استبيانات تفاعلية", en: "Interactive Surveys", descAr: "نفسية، شخصية، اجتماعية، بحوث، أخرى", descEn: "Psychological, personality, social, research, others" },
          { ar: "اختبارات تفاعلية", en: "Interactive Quizzes", descAr: "نفسية، شخصية، اجتماعية، بحوث، أخرى", descEn: "Psychological, personality, social, research, others" },
          { ar: "حاسبات تفاعلية", en: "Interactive Calculators", descAr: "Interactive Calculators", descEn: "Interactive calculators" },
          { ar: "خرائط تفاعلية", en: "Interactive Maps", descAr: "Interactive Maps", descEn: "Interactive maps" },
          { ar: "عروض تقديمية تفاعلية", en: "Interactive Presentations", descAr: "Interactive Presentations", descEn: "Interactive presentations" },
          { ar: "إنفوجرافيك تفاعلي", en: "Interactive Infographics", descAr: "Interactive Infographics", descEn: "Interactive infographics" },
          { ar: "جولات افتراضية", en: "Virtual Tours", descAr: "Virtual Tours", descEn: "Virtual tours" },
          { ar: "نماذج تفاعلية", en: "Interactive Forms", descAr: "Interactive Forms", descEn: "Interactive forms" },
          { ar: "Timeline تفاعلي", en: "Interactive Timelines", descAr: "Interactive Timelines", descEn: "Interactive timelines" },
          { ar: "Dashboard Templates", en: "Dashboard Templates", descAr: "لوحات تحكم", descEn: "Dashboards" },
        ],
      },
    ],
  },
  {
    ar: "محتوى البرمجة والتقنية", en: "Programming & Tech Content", icon: "💻",
    children: [
      {
        ar: "الأكواد والسكريبتات", en: "Code & Scripts", icon: "⌨️",
        children: [
          { ar: "قوالب ومقتطفات أكواد جاهزة", en: "Code Templates", descAr: "Code Templates", descEn: "Code templates" },
          { ar: "سكريبتات Python", en: "Python Scripts", descAr: "Python Scripts", descEn: "Python scripts" },
          { ar: "سكريبتات JavaScript", en: "JavaScript Scripts", descAr: "JS Scripts", descEn: "JS scripts" },
          { ar: "سكريبتات PHP", en: "PHP Scripts", descAr: "PHP Scripts", descEn: "PHP scripts" },
          { ar: "سكريبتات Bash", en: "Shell Scripts", descAr: "Shell Scripts", descEn: "Shell scripts" },
          { ar: "سكربتات Pine تريدنج فيو", en: "TradingView Pine Scripts", descAr: "Pine Scripts", descEn: "Pine scripts" },
          { ar: "مقتطفات أكواد", en: "Code Snippets", descAr: "Code Snippets", descEn: "Code snippets" },
          { ar: "Regular Expressions", en: "Regular Expressions", descAr: "تعبيرات نمطية", descEn: "Regex patterns" },
          { ar: "SQL Queries", en: "SQL Queries", descAr: "استعلامات قواعد البيانات", descEn: "Database queries" },
          { ar: "API Collections", en: "API Collections", descAr: "مجموعات API", descEn: "API collections" },
          { ar: "Postman Collections", en: "Postman Collections", descAr: "مجموعات Postman", descEn: "Postman collections" },
        ],
      },
      {
        ar: "الإضافات والمكونات", en: "Plugins & Components", icon: "🔌",
        children: [
          { ar: "إضافات WordPress", en: "WordPress Plugins", descAr: "WP Plugins", descEn: "WP plugins" },
          { ar: "إضافات Shopify", en: "Shopify Apps", descAr: "Shopify Apps", descEn: "Shopify apps" },
          { ar: "إضافات Chrome", en: "Chrome Extensions", descAr: "Browser Extensions", descEn: "Browser extensions" },
          { ar: "إضافات VS Code", en: "VS Code Extensions", descAr: "Code Editor Extensions", descEn: "Code editor extensions" },
          { ar: "إضافات Photoshop", en: "Photoshop Plugins", descAr: "PS Plugins", descEn: "PS plugins" },
          { ar: "إضافات Excel", en: "Excel Add-ins", descAr: "Excel Add-ins", descEn: "Excel add-ins" },
          { ar: "Libraries", en: "Libraries", descAr: "مكتبات برمجية", descEn: "Programming libraries" },
          { ar: "Frameworks", en: "Frameworks", descAr: "أطر عمل", descEn: "Frameworks" },
          { ar: "APIs", en: "APIs", descAr: "واجهات برمجية", descEn: "Programming interfaces" },
          { ar: "SDKs", en: "SDKs", descAr: "حزم تطوير", descEn: "Development kits" },
          { ar: "مكونات إضافية أخرى وإضافات متصفح أخرى", en: "Other Plugins & Add-ons", descAr: "Other Plugins/Add-ons", descEn: "Other plugins/add-ons" },
        ],
      },
      {
        ar: "قوالب التقنية والبيانات", en: "Tech & Data Templates", icon: "🗄️",
        children: [
          { ar: "قوالب قواعد البيانات", en: "Database Templates", descAr: "Database Templates", descEn: "Database templates" },
          { ar: "Docker Templates", en: "Docker Templates", descAr: "Docker Configurations", descEn: "Docker configurations" },
          { ar: "Kubernetes Templates", en: "Kubernetes Templates", descAr: "K8s Configurations", descEn: "K8s configurations" },
          { ar: "CI/CD Pipelines", en: "CI/CD Pipelines", descAr: "خطوط إنتاج", descEn: "Delivery pipelines" },
          { ar: "Infrastructure as Code", en: "Infrastructure as Code", descAr: "قوالب البنية التحتية", descEn: "Infrastructure templates" },
          { ar: "Cloud Templates", en: "Cloud Templates", descAr: "قوالب سحابية", descEn: "Cloud templates" },
          { ar: "مؤشرات Trading View", en: "TradingView Indicators", descAr: "Trading Indicators", descEn: "Trading indicators" },
          { ar: "Expert Advisors", en: "Expert Advisors", descAr: "روبوتات تداول", descEn: "Trading robots" },
          { ar: "Blockchain Smart Contracts", en: "Blockchain Smart Contracts", descAr: "عقود ذكية", descEn: "Smart contracts" },
          { ar: "Machine Learning Models", en: "Machine Learning Models", descAr: "نماذج تعلم آلة", descEn: "ML models" },
        ],
      },
      {
        ar: "قوالب المواقع والتطبيقات", en: "Website & App Templates", icon: "🌐",
        children: [
          { ar: "قوالب WordPress", en: "WordPress Themes", descAr: "ثيمات ووردبريس", descEn: "WordPress themes" },
          { ar: "قوالب Shopify", en: "Shopify Themes", descAr: "متاجر إلكترونية", descEn: "E-commerce stores" },
          { ar: "قوالب HTML/CSS", en: "HTML/CSS Templates", descAr: "مواقع ثابتة", descEn: "Static websites" },
          { ar: "قوالب React", en: "React Templates", descAr: "تطبيقات React", descEn: "React apps" },
          { ar: "قوالب Vue", en: "Vue Templates", descAr: "تطبيقات Vue", descEn: "Vue apps" },
          { ar: "قوالب Angular", en: "Angular Templates", descAr: "تطبيقات Angular", descEn: "Angular apps" },
          { ar: "قوالب Bootstrap", en: "Bootstrap Templates", descAr: "تصاميم Bootstrap", descEn: "Bootstrap designs" },
          { ar: "قوالب Landing Pages", en: "Landing Page Templates", descAr: "صفحات هبوط", descEn: "Landing pages" },
          { ar: "قوالب Email", en: "Email Templates", descAr: "رسائل بريدية", descEn: "Email messages" },
          { ar: "قوالب Mobile Apps", en: "Mobile App Templates", descAr: "تطبيقات موبايل", descEn: "Mobile apps" },
          { ar: "جميع أنواع قوالب المواقع والتطبيقات الأخرى", en: "All Other Website & App Templates", descAr: "قوالب متاجر إلكترونية، قوالب مواقع ومنصات وأنظمة، قوالب تطبيقات، قوالب صفحات هبوط وواجهات مستخدم، قوالب برامج جاهزة، قوالب محتوى المواقع الإلكترونية web copy", descEn: "E-commerce templates, website/platform/system templates, app templates, landing pages and UI templates, ready software templates, web copy templates" },
          { ar: "حلول وأنظمة برمجية معدة مسبقًا", en: "Pre-built Software Solutions & Systems", descAr: "لمعالجة مشكلات محددة، مثل نظام بسيط لإدارة المخزون أو نظام لتحليل النسب المالية", descEn: "For specific problems, e.g. a simple inventory management system or a financial ratio analysis system" },
        ],
      },
    ],
  },
  {
    ar: "المنتجات الرقمية المتخصصة", en: "Specialized Digital Products", icon: "🚀",
    children: [
      {
        ar: "NFTs والأصول الرقمية", en: "NFTs & Digital Assets", icon: "🪙",
        children: [
          { ar: "فن رقمي NFT", en: "Digital Art NFTs", descAr: "Digital Art NFTs", descEn: "Digital art NFTs" },
          { ar: "مقتنيات NFT", en: "Collectible NFTs", descAr: "Collectible NFTs", descEn: "Collectible NFTs" },
          { ar: "NFTs الألعاب", en: "Gaming NFTs", descAr: "Gaming NFTs", descEn: "Gaming NFTs" },
          { ar: "NFTs الموسيقى", en: "Music NFTs", descAr: "Music NFTs", descEn: "Music NFTs" },
          { ar: "NFTs العقارات الافتراضية", en: "Virtual Real Estate NFTs", descAr: "Virtual Real Estate", descEn: "Virtual real estate" },
          { ar: "أفاتار NFT", en: "Avatar NFTs", descAr: "Avatar NFTs", descEn: "Avatar NFTs" },
          { ar: "Domain NFTs", en: "Domain NFTs", descAr: "نطاقات Web3", descEn: "Web3 domains" },
          { ar: "Membership NFTs", en: "Membership NFTs", descAr: "عضويات NFT", descEn: "NFT memberships" },
          { ar: "Utility NFTs", en: "Utility NFTs", descAr: "NFTs وظيفية", descEn: "Functional NFTs" },
          { ar: "AR/VR NFTs", en: "AR/VR NFTs", descAr: "واقع معزز/افتراضي", descEn: "Augmented/virtual reality" },
        ],
      },
      {
        ar: "المحتوى ثلاثي الأبعاد", en: "3D Content", icon: "🧊",
        children: [
          { ar: "نماذج 3D جاهزة", en: "3D Models", descAr: "3D Models", descEn: "3D models" },
          { ar: "مواد وخامات 3D", en: "3D Materials", descAr: "3D Materials", descEn: "3D materials" },
          { ar: "أنيميشن 3D", en: "3D Animations", descAr: "3D Animations", descEn: "3D animations" },
          { ar: "بيئات 3D", en: "3D Environments", descAr: "3D Environments", descEn: "3D environments" },
          { ar: "شخصيات 3D", en: "3D Characters", descAr: "3D Characters", descEn: "3D characters" },
          { ar: "أثاث 3D", en: "3D Furniture", descAr: "3D Furniture", descEn: "3D furniture" },
          { ar: "سيارات 3D", en: "3D Vehicles", descAr: "3D Vehicles", descEn: "3D vehicles" },
          { ar: "نباتات 3D", en: "3D Plants", descAr: "3D Plants", descEn: "3D plants" },
          { ar: "معمار 3D", en: "3D Architecture", descAr: "3D Architecture", descEn: "3D architecture" },
          { ar: "ملابس 3D", en: "3D Clothing", descAr: "3D Clothing", descEn: "3D clothing" },
        ],
      },
      {
        ar: "المحتوى للواقع الافتراضي والمعزز", en: "VR & AR Content", icon: "🥽",
        children: [
          { ar: "تطبيقات VR", en: "VR Applications", descAr: "VR Applications", descEn: "VR applications" },
          { ar: "ألعاب VR", en: "VR Games", descAr: "VR Games", descEn: "VR games" },
          { ar: "جولات VR", en: "VR Tours", descAr: "VR Tours", descEn: "VR tours" },
          { ar: "تدريب VR", en: "VR Training", descAr: "VR Training", descEn: "VR training" },
          { ar: "فلاتر AR", en: "AR Filters", descAr: "AR Filters", descEn: "AR filters" },
          { ar: "تطبيقات AR", en: "AR Applications", descAr: "AR Applications", descEn: "AR applications" },
          { ar: "ألعاب AR", en: "AR Games", descAr: "AR Games", descEn: "AR games" },
          { ar: "كتب AR", en: "AR Books", descAr: "AR Books", descEn: "AR books" },
          { ar: "بطاقات AR", en: "AR Cards", descAr: "AR Cards", descEn: "AR cards" },
          { ar: "تجارب Metaverse", en: "Metaverse Experiences", descAr: "Metaverse Experiences", descEn: "Metaverse experiences" },
        ],
      },
    ],
  },
  {
    ar: "الخدمات الاشتراكية والعضويات", en: "Subscriptions & Memberships", icon: "🔁",
    children: [
      {
        ar: "المحتوى الاشتراكي", en: "Subscription Content", icon: "📬",
        children: [
          { ar: "نشرات إخبارية ومدونات ومقالات مدفوعة", en: "Premium Newsletters", descAr: "Premium Newsletters", descEn: "Premium newsletters" },
          { ar: "محتوى حصري", en: "Exclusive Content", descAr: "Exclusive Content", descEn: "Exclusive content" },
          { ar: "مكتبات موارد", en: "Resource Libraries", descAr: "Resource Libraries", descEn: "Resource libraries" },
          { ar: "قوالب شهرية", en: "Monthly Templates", descAr: "Monthly Templates", descEn: "Monthly templates" },
          { ar: "اشتراك Stock Assets", en: "Stock Assets Subscription", descAr: "اشتراكات الموارد", descEn: "Asset subscriptions" },
          { ar: "دورات اشتراكية", en: "Subscription Courses", descAr: "Subscription Courses", descEn: "Subscription courses" },
          { ar: "Coaching Programs", en: "Coaching Programs", descAr: "برامج تدريب", descEn: "Coaching programs" },
          { ar: "Mastermind Groups", en: "Mastermind Groups", descAr: "مجموعات احترافية", descEn: "Professional groups" },
          { ar: "Community Access", en: "Community Access", descAr: "وصول للمجتمع", descEn: "Community access" },
          { ar: "Premium Support", en: "Premium Support", descAr: "دعم مميز", descEn: "Premium support" },
        ],
      },
      {
        ar: "منصات SaaS والخدمات السحابية", en: "SaaS Platforms & Cloud Services", icon: "☁️",
        children: [
          { ar: "منصات إدارة المشاريع", en: "Project Management SaaS", descAr: "Project Management SaaS", descEn: "Project management SaaS" },
          { ar: "منصات CRM", en: "CRM Platforms", descAr: "Customer Relationship Management", descEn: "Customer relationship management" },
          { ar: "منصات التسويق", en: "Marketing Automation Platforms", descAr: "Marketing Automation Platforms", descEn: "Marketing automation platforms" },
          { ar: "منصات التحليلات", en: "Analytics Platforms", descAr: "Analytics Platforms", descEn: "Analytics platforms" },
          { ar: "منصات التعليم", en: "Learning Management Systems", descAr: "Learning Management Systems", descEn: "Learning management systems" },
          { ar: "منصات المحاسبة", en: "Accounting Software", descAr: "Accounting Software", descEn: "Accounting software" },
          { ar: "منصات التصميم", en: "Design Platforms", descAr: "Design Platforms", descEn: "Design platforms" },
          { ar: "منصات التخزين السحابي", en: "Cloud Storage", descAr: "Cloud Storage", descEn: "Cloud storage" },
          { ar: "منصات الأمان السحابي", en: "Cloud Security Platforms", descAr: "Security Platforms", descEn: "Security platforms" },
          { ar: "منصات التواصل", en: "Communication Platforms", descAr: "Communication Platforms", descEn: "Communication platforms" },
        ],
      },
    ],
  },
];

// ============================================================
// B — الخدمات الرقمية المتخصصة حسب الطلب ذات الدخل الإيجابي
// ============================================================
export const SERVICE_CATALOG: CatalogEntry[] = [
  {
    ar: "خدمات الكتابة والمحتوى", en: "Writing & Content Services", icon: "✍️",
    children: [
      {
        ar: "خدمات كتابة المحتوى", en: "Content Writing Services", icon: "📝",
        children: [
          { ar: "كتابة المقالات", en: "Article Writing", descAr: "مقالات متخصصة، مقالات SEO", descEn: "Specialized articles, SEO articles" },
          { ar: "كتابة المدونات", en: "Blog Writing", descAr: "محتوى مدونات، Guest Posts", descEn: "Blog content, guest posts" },
          { ar: "كتابة النصوص التسويقية", en: "Copywriting", descAr: "Copywriting، Sales Copy", descEn: "Copywriting, sales copy" },
          { ar: "أوصاف المنتجات", en: "Product Descriptions", descAr: "وصف منتجات التجارة الإلكترونية", descEn: "E-commerce product descriptions" },
          { ar: "النصوص الإعلانية", en: "Ad Copy", descAr: "إعلانات، حملات تسويقية", descEn: "Ads, marketing campaigns" },
          { ar: "كتابة السيناريوهات", en: "Script Writing", descAr: "سيناريوهات فيديو، أفلام", descEn: "Video scripts, films" },
          { ar: "كتابة البودكاست", en: "Podcast Writing", descAr: "نصوص بودكاست، حوارات", descEn: "Podcast scripts, dialogues" },
          { ar: "كتابة المحتوى التقني", en: "Technical Writing", descAr: "Technical Writing", descEn: "Technical writing" },
          { ar: "كتابة المحتوى الطبي", en: "Medical Writing", descAr: "Medical Writing", descEn: "Medical writing" },
          { ar: "كتابة المحتوى القانوني", en: "Legal Writing", descAr: "Legal Writing", descEn: "Legal writing" },
          { ar: "Ghost Writing", en: "Ghost Writing", descAr: "الكتابة الشبحية", descEn: "Ghostwriting" },
          { ar: "كتابة السيرة الذاتية", en: "CV Writing", descAr: "CV Writing", descEn: "CV writing" },
          { ar: "بحوث وتقارير وتحليلات ودراسات", en: "Research, Reports, Analysis & Studies", descAr: "كل أنواع البحوث والدراسات والتحليلات والتقارير", descEn: "All types of research, studies, analysis and reports" },
          { ar: "إعداد محتوى ورش عمل ودورات تدريبية", en: "Workshop & Training Course Content Preparation", descAr: "إعداد محتوى تدريبي", descEn: "Training content preparation" },
          { ar: "محتويات نصية أخرى", en: "Other Text Content", descAr: "محتويات نصية متنوعة", descEn: "Miscellaneous text content" },
        ],
      },
      {
        ar: "خدمات التحرير والترجمة", en: "Editing & Translation Services", icon: "🌍",
        children: [
          { ar: "التحرير اللغوي", en: "Editing & Proofreading", descAr: "Editing، Proofreading", descEn: "Editing, proofreading" },
          { ar: "التدقيق اللغوي", en: "Grammar & Spelling Check", descAr: "Grammar، Spelling Check", descEn: "Grammar, spelling check" },
          { ar: "الترجمة العامة", en: "General Translation", descAr: "ترجمة نصوص عامة", descEn: "General text translation" },
          { ar: "الترجمة المتخصصة", en: "Specialized Translation", descAr: "طبية، قانونية، تقنية", descEn: "Medical, legal, technical" },
          { ar: "الترجمة الفورية", en: "Simultaneous Translation", descAr: "Simultaneous Translation", descEn: "Simultaneous translation" },
          { ar: "التعريب", en: "Localization", descAr: "Localization", descEn: "Localization" },
          { ar: "Transcription", en: "Transcription", descAr: "تفريغ صوتي", descEn: "Audio transcription" },
          { ar: "Subtitling", en: "Subtitling", descAr: "كتابة الترجمة", descEn: "Subtitle writing" },
          { ar: "إعادة الكتابة", en: "Rewriting", descAr: "Rewriting", descEn: "Rewriting" },
          { ar: "التلخيص", en: "Summarization", descAr: "Summarization", descEn: "Summarization" },
        ],
      },
    ],
  },
  {
    ar: "خدمات التصميم والإبداع", en: "Design & Creative Services", icon: "🎨",
    children: [
      {
        ar: "التصميم الجرافيكي", en: "Graphic Design", icon: "🖌️",
        children: [
          { ar: "تصميم الشعارات", en: "Logo Design", descAr: "Logo Design", descEn: "Logo design" },
          { ar: "الهوية البصرية", en: "Brand Identity", descAr: "Brand Identity", descEn: "Brand identity" },
          { ar: "تصميم البوسترات", en: "Poster Design", descAr: "Poster Design", descEn: "Poster design" },
          { ar: "تصميم البروشورات", en: "Brochure Design", descAr: "Brochure Design", descEn: "Brochure design" },
          { ar: "تصميم الكتب", en: "Book Design", descAr: "Book Design", descEn: "Book design" },
          { ar: "تصميم الأغلفة", en: "Cover Design", descAr: "Cover Design", descEn: "Cover design" },
          { ar: "تصميم البطاقات", en: "Card Design", descAr: "Card Design", descEn: "Card design" },
          { ar: "تصميم التغليف", en: "Package Design", descAr: "Package Design", descEn: "Package design" },
          { ar: "تصميم الإعلانات", en: "Ad Design", descAr: "Ad Design", descEn: "Ad design" },
          { ar: "تصميم السوشيال ميديا", en: "Social Media Graphics", descAr: "Social Media Graphics", descEn: "Social media graphics" },
          { ar: "تصميم البانرات", en: "Banner Design", descAr: "Banner Design", descEn: "Banner design" },
          { ar: "الرسم الرقمي", en: "Digital Illustration", descAr: "Digital Illustration", descEn: "Digital illustration" },
          { ar: "تنقيح وتعديل الصور", en: "Photo Retouching & Editing", descAr: "تعديل وتحسين الصور", descEn: "Photo editing and enhancement" },
        ],
      },
      {
        ar: "التصميم والطباعة", en: "Design & Print", icon: "👕",
        children: [
          { ar: "تصاميم التيشيرتات", en: "T-shirt Designs", descAr: "T-shirt Designs", descEn: "T-shirt designs" },
          { ar: "تصاميم الأكواب", en: "Mug Designs", descAr: "Mug Designs", descEn: "Mug designs" },
          { ar: "تصاميم الحقائب", en: "Bag Designs", descAr: "Bag Designs", descEn: "Bag designs" },
          { ar: "تصاميم البوسترات", en: "Poster Designs", descAr: "Poster Designs", descEn: "Poster designs" },
          { ar: "تصاميم الملصقات", en: "Sticker Designs", descAr: "Sticker Designs", descEn: "Sticker designs" },
          { ar: "تصاميم القبعات", en: "Hat Designs", descAr: "Hat Designs", descEn: "Hat designs" },
          { ar: "تصاميم الوسائد", en: "Pillow Designs", descAr: "Pillow Designs", descEn: "Pillow designs" },
          { ar: "تصاميم الهواتف", en: "Phone Case Designs", descAr: "Phone Case Designs", descEn: "Phone case designs" },
          { ar: "تصاميم اللوحات", en: "Canvas Prints", descAr: "Canvas Prints", descEn: "Canvas prints" },
          { ar: "تصاميم البطاقات وبطاقات الأعمال", en: "Card & Business Card Designs", descAr: "Card Designs", descEn: "Card designs" },
          { ar: "تصاميم دعوات وبطاقات التهنئة", en: "Invitation & Greeting Card Designs", descAr: "دعوات وتهنئة", descEn: "Invitations and greetings" },
          { ar: "تصاميم شهادات", en: "Certificate Designs", descAr: "شهادات", descEn: "Certificates" },
        ],
      },
      {
        ar: "تصميم المواقع والتطبيقات", en: "Web & App Design", icon: "📱",
        children: [
          { ar: "تصميم UI", en: "UI Design", descAr: "واجهة المستخدم", descEn: "User interface" },
          { ar: "تصميم UX", en: "UX Design", descAr: "تجربة المستخدم", descEn: "User experience" },
          { ar: "تصميم المواقع", en: "Web Design", descAr: "Web Design", descEn: "Web design" },
          { ar: "تصميم التطبيقات", en: "App Design", descAr: "App Design", descEn: "App design" },
          { ar: "تصميم Dashboard", en: "Dashboard Design", descAr: "لوحات التحكم", descEn: "Dashboards" },
          { ar: "Wireframing", en: "Wireframing", descAr: "المخططات الأولية", descEn: "Initial schematics" },
          { ar: "Prototyping", en: "Prototyping", descAr: "النماذج الأولية", descEn: "Prototypes" },
          { ar: "تصميم الأيقونات", en: "Icon Design", descAr: "Icon Design", descEn: "Icon design" },
          { ar: "تصميم التفاعل", en: "Interaction Design", descAr: "Interaction Design", descEn: "Interaction design" },
          { ar: "تصميم الاستجابة", en: "Responsive Design", descAr: "Responsive Design", descEn: "Responsive design" },
        ],
      },
    ],
  },
  {
    ar: "خدمات الصوت والفيديو", en: "Audio & Video Services", icon: "🎙️",
    children: [
      {
        ar: "الخدمات الصوتية", en: "Audio Services", icon: "🎧",
        children: [
          { ar: "التعليق الصوتي", en: "Voice Over", descAr: "Voice Over", descEn: "Voice over" },
          { ar: "إنتاج البودكاست", en: "Podcast Production", descAr: "تسجيل، تحرير، هندسة صوتية", descEn: "Recording, editing, audio engineering" },
          { ar: "تأليف الموسيقى", en: "Music Composition", descAr: "Music Composition", descEn: "Music composition" },
          { ar: "المؤثرات الصوتية", en: "Sound Effects Creation", descAr: "Sound Effects Creation", descEn: "Sound effects creation" },
          { ar: "الميكساج والماسترنج", en: "Audio Mixing & Mastering", descAr: "Audio Mixing & Mastering", descEn: "Audio mixing & mastering" },
          { ar: "تسجيل وتأليف الأغاني", en: "Song Recording & Writing", descAr: "Song Recording", descEn: "Song recording" },
          { ar: "الإنتاج الموسيقي", en: "Music Production", descAr: "Music Production", descEn: "Music production" },
          { ar: "تحرير الصوت", en: "Audio Editing", descAr: "Audio Editing", descEn: "Audio editing" },
          { ar: "ترميم الصوت", en: "Audio Restoration", descAr: "Audio Restoration", descEn: "Audio restoration" },
          { ar: "Foley Art", en: "Foley Art", descAr: "مؤثرات صوتية سينمائية", descEn: "Cinematic sound effects" },
        ],
      },
      {
        ar: "خدمات الفيديو", en: "Video Services", icon: "🎬",
        children: [
          { ar: "إنتاج الفيديو", en: "Video Production", descAr: "تصوير، مونتاج، إخراج، إعلانات، أفلام قصيرة، أفلام سينمائية، تغطيات", descEn: "Filming, editing, directing, ads, short films, cinema films, coverage" },
          { ar: "تصوير الفعاليات والمناسبات", en: "Event Coverage", descAr: "Event Coverage", descEn: "Event coverage" },
          { ar: "تصوير المنتجات", en: "Product Photography", descAr: "Product Photography", descEn: "Product photography" },
          { ar: "المونتاج", en: "Video Editing", descAr: "Video Editing", descEn: "Video editing" },
          { ar: "الموشن جرافيك", en: "Motion Graphics", descAr: "Motion Graphics", descEn: "Motion graphics" },
          { ar: "الرسوم المتحركة 2D", en: "2D Animation", descAr: "2D Animation", descEn: "2D animation" },
          { ar: "الرسوم المتحركة 3D", en: "3D Animation", descAr: "3D Animation", descEn: "3D animation" },
          { ar: "المؤثرات البصرية VFX", en: "Visual Effects (VFX)", descAr: "Visual Effects", descEn: "Visual effects" },
          { ar: "تصحيح الألوان", en: "Color Grading", descAr: "Color Grading", descEn: "Color grading" },
          { ar: "البث المباشر", en: "Live Streaming", descAr: "Live Streaming", descEn: "Live streaming" },
        ],
      },
    ],
  },
  {
    ar: "خدمات البرمجة والتطوير", en: "Programming & Development Services", icon: "💻",
    children: [
      {
        ar: "تطوير المواقع الكاملة", en: "Full Website Development", icon: "🌐",
        children: [
          { ar: "تطوير Frontend", en: "Frontend Development", descAr: "HTML, CSS, JavaScript", descEn: "HTML, CSS, JavaScript" },
          { ar: "تطوير Backend", en: "Backend Development", descAr: "Server-side Development", descEn: "Server-side development" },
          { ar: "Full Stack Development", en: "Full Stack Development", descAr: "بناء وتطوير مواقع وتطبيقات كاملة End to End & Full Stack Apps and Webs", descEn: "End-to-end full stack apps and websites" },
          { ar: "تطوير WordPress", en: "WordPress Development", descAr: "مواقع ووردبريس", descEn: "WordPress websites" },
          { ar: "تطوير Shopify", en: "Shopify Development", descAr: "متاجر شوبيفاي", descEn: "Shopify stores" },
          { ar: "تطوير Laravel", en: "Laravel Development", descAr: "تطبيقات Laravel", descEn: "Laravel apps" },
          { ar: "تطوير React", en: "React Development", descAr: "تطبيقات React", descEn: "React apps" },
          { ar: "تطوير Vue", en: "Vue Development", descAr: "تطبيقات Vue", descEn: "Vue apps" },
          { ar: "تطوير Angular", en: "Angular Development", descAr: "تطبيقات Angular", descEn: "Angular apps" },
          { ar: "تطوير API", en: "API Development", descAr: "واجهات برمجية", descEn: "Programming interfaces" },
          { ar: "تطوير CMS", en: "CMS Development", descAr: "أنظمة إدارة محتوى", descEn: "Content management systems" },
          { ar: "صيانة المواقع ودعم فني", en: "Website Maintenance & Support", descAr: "Website Maintenance", descEn: "Website maintenance" },
          { ar: "تخصيص السكربتات والبرمجيات والمكونات الإضافية", en: "Scripts, Software & Plugin Customization", descAr: "تخصيص برمجي", descEn: "Software customization" },
          { ar: "حلول مؤسسية متخصصة", en: "Specialized Enterprise Solutions", descAr: "حلول للمؤسسات", descEn: "Enterprise solutions" },
          { ar: "اختبار البرمجيات (Testing)", en: "Software Testing", descAr: "اختبار وجودة البرمجيات", descEn: "Software testing and QA" },
          { ar: "التكامل البرمجي (System Integration)", en: "System Integration", descAr: "تكامل الأنظمة", descEn: "System integration" },
        ],
      },
      {
        ar: "تطوير التطبيقات الكاملة", en: "Full App Development", icon: "📱",
        children: [
          { ar: "تطوير iOS", en: "iOS Development", descAr: "تطبيقات آيفون", descEn: "iPhone apps" },
          { ar: "تطوير Android", en: "Android Development", descAr: "تطبيقات أندرويد", descEn: "Android apps" },
          { ar: "تطوير Cross-Platform", en: "Cross-Platform Development", descAr: "Flutter، React Native", descEn: "Flutter, React Native" },
          { ar: "تطوير Desktop Apps", en: "Desktop App Development", descAr: "تطبيقات سطح المكتب", descEn: "Desktop applications" },
          { ar: "تطوير PWA", en: "PWA Development", descAr: "Progressive Web Apps", descEn: "Progressive web apps" },
          { ar: "تطوير الألعاب", en: "Game Development", descAr: "Game Development", descEn: "Game development" },
          { ar: "تطوير VR/AR", en: "VR/AR Development", descAr: "تطبيقات الواقع الافتراضي", descEn: "Virtual reality apps" },
          { ar: "تطوير IoT", en: "IoT Development", descAr: "إنترنت الأشياء", descEn: "Internet of Things" },
          { ar: "تطوير Blockchain", en: "Blockchain Development", descAr: "تطبيقات البلوكشين", descEn: "Blockchain apps" },
          { ar: "تطوير AI/ML", en: "AI/ML Development", descAr: "الذكاء الاصطناعي", descEn: "Artificial intelligence" },
        ],
      },
    ],
  },
  {
    ar: "التسويق الرقمي والأعمال", en: "Digital Marketing & Business", icon: "📈",
    children: [
      {
        ar: "خدمات التسويق الرقمي", en: "Digital Marketing Services", icon: "📣",
        children: [
          { ar: "تحسين محركات البحث SEO", en: "SEO", descAr: "On-page، Off-page SEO", descEn: "On-page, off-page SEO" },
          { ar: "التسويق بالمحتوى", en: "Content Marketing", descAr: "Content Marketing", descEn: "Content marketing" },
          { ar: "إدارة السوشيال ميديا", en: "Social Media Management", descAr: "Social Media Management", descEn: "Social media management" },
          { ar: "الإعلانات المدفوعة PPC", en: "Paid Ads (PPC)", descAr: "Google Ads، Facebook Ads", descEn: "Google Ads, Facebook Ads" },
          { ar: "التسويق بالبريد الإلكتروني", en: "Email Marketing", descAr: "Email Marketing", descEn: "Email marketing" },
          { ar: "التسويق بالعمولة", en: "Affiliate Marketing", descAr: "Affiliate Marketing", descEn: "Affiliate marketing" },
          { ar: "التسويق بالمؤثرين", en: "Influencer Marketing", descAr: "Influencer Marketing", descEn: "Influencer marketing" },
          { ar: "تحليل البيانات", en: "Analytics & Reporting", descAr: "Analytics & Reporting", descEn: "Analytics & reporting" },
          { ar: "استراتيجيات التسويق", en: "Marketing Strategy", descAr: "Marketing Strategy", descEn: "Marketing strategy" },
          { ar: "تحسين معدل التحويل CRO", en: "Conversion Rate Optimization", descAr: "Conversion Optimization", descEn: "Conversion optimization" },
          { ar: "Growth Hacking", en: "Growth Hacking", descAr: "النمو السريع", descEn: "Rapid growth" },
          { ar: "Marketing Automation", en: "Marketing Automation", descAr: "أتمتة التسويق", descEn: "Marketing automation" },
        ],
      },
      {
        ar: "الاستشارات والخدمات المهنية", en: "Consulting & Professional Services", icon: "💼",
        children: [
          { ar: "استشارات الأعمال", en: "Business Consulting", descAr: "Business Consulting", descEn: "Business consulting" },
          { ar: "استشارات التسويق", en: "Marketing Consulting", descAr: "Marketing Consulting", descEn: "Marketing consulting" },
          { ar: "استشارات مالية", en: "Financial Consulting", descAr: "Financial Consulting", descEn: "Financial consulting" },
          { ar: "استشارات تقنية وبرمجية", en: "IT Consulting", descAr: "IT Consulting", descEn: "IT consulting" },
          { ar: "استشارات الموارد البشرية", en: "HR Consulting", descAr: "HR Consulting", descEn: "HR consulting" },
          { ar: "استشارات قانونية", en: "Legal Consulting", descAr: "Legal Consulting", descEn: "Legal consulting" },
          { ar: "استشارات الإدارة", en: "Management Consulting", descAr: "Management Consulting", descEn: "Management consulting" },
          { ar: "دراسات الجدوى", en: "Feasibility Studies", descAr: "Feasibility Studies", descEn: "Feasibility studies" },
          { ar: "أبحاث السوق", en: "Market Research", descAr: "Market Research", descEn: "Market research" },
          { ar: "تخطيط الأعمال", en: "Business Planning", descAr: "Business Planning", descEn: "Business planning" },
          { ar: "إدارة المشاريع", en: "Project Management", descAr: "Project Management", descEn: "Project management" },
          { ar: "Virtual Assistant", en: "Virtual Assistant", descAr: "مساعد افتراضي", descEn: "Virtual assistant" },
          { ar: "استشارات توجيه وإرشاد نفسي وذاتي ووعي وتطوير ذاتي", en: "Psychological Guidance, Self-Awareness & Development Consulting", descAr: "توجيه وإرشاد وتطوير ذاتي", descEn: "Guidance, counseling and self-development" },
        ],
      },
    ],
  },
  {
    ar: "التعليم والتدريب", en: "Education & Training", icon: "🎓",
    children: [
      {
        ar: "التدريس والتعليم عبر الإنترنت", en: "Online Teaching & Tutoring", icon: "👨‍🏫",
        children: [
          { ar: "التدريس الخصوصي", en: "Private Tutoring", descAr: "دروس خصوصية أونلاين", descEn: "Online private lessons" },
          { ar: "تعليم اللغات", en: "Language Teaching", descAr: "Language Teaching", descEn: "Language teaching" },
          { ar: "تعليم البرمجة", en: "Programming Tutoring", descAr: "Programming Tutoring", descEn: "Programming tutoring" },
          { ar: "تعليم الموسيقى", en: "Music Lessons", descAr: "Music Lessons", descEn: "Music lessons" },
          { ar: "تعليم الفنون", en: "Art Classes", descAr: "Art Classes", descEn: "Art classes" },
          { ar: "التعليم الأكاديمي", en: "Academic Tutoring", descAr: "Academic Tutoring", descEn: "Academic tutoring" },
          { ar: "تعليم المهارات", en: "Skills Training", descAr: "Skills Training", descEn: "Skills training" },
          { ar: "تحضير الامتحانات", en: "Test Preparation", descAr: "Test Preparation", descEn: "Test preparation" },
          { ar: "IELTS/TOEFL", en: "IELTS/TOEFL Preparation", descAr: "تحضير اختبارات اللغة", descEn: "Language test preparation" },
          { ar: "SAT/GRE", en: "SAT/GRE Preparation", descAr: "تحضير اختبارات القبول", descEn: "Admission test preparation" },
        ],
      },
      {
        ar: "التدريب والتطوير المهني", en: "Coaching & Professional Development", icon: "🚀",
        children: [
          { ar: "Life Coaching", en: "Life Coaching", descAr: "التدريب على الحياة", descEn: "Life coaching" },
          { ar: "Business Coaching", en: "Business Coaching", descAr: "تدريب الأعمال", descEn: "Business coaching" },
          { ar: "Career Coaching", en: "Career Coaching", descAr: "التوجيه المهني", descEn: "Career guidance" },
          { ar: "Executive Coaching", en: "Executive Coaching", descAr: "تدريب التنفيذيين", descEn: "Executive coaching" },
          { ar: "Leadership Training", en: "Leadership Training", descAr: "تدريب القيادة", descEn: "Leadership training" },
          { ar: "Soft Skills Training", en: "Soft Skills Training", descAr: "المهارات الناعمة", descEn: "Soft skills" },
          { ar: "Technical Training", en: "Technical Training", descAr: "التدريب التقني", descEn: "Technical training" },
          { ar: "Sales Training", en: "Sales Training", descAr: "تدريب المبيعات", descEn: "Sales training" },
          { ar: "Customer Service Training", en: "Customer Service Training", descAr: "تدريب خدمة العملاء", descEn: "Customer service training" },
          { ar: "Team Building", en: "Team Building", descAr: "بناء الفريق", descEn: "Team building" },
        ],
      },
    ],
  },
  {
    ar: "الخدمات المتخصصة", en: "Specialized Services", icon: "🔬",
    children: [
      {
        ar: "خدمات البيانات والتحليل", en: "Data & Analytics Services", icon: "📊",
        children: [
          { ar: "تحليل البيانات", en: "Data Analysis", descAr: "Data Analysis", descEn: "Data analysis" },
          { ar: "علم البيانات", en: "Data Science", descAr: "Data Science", descEn: "Data science" },
          { ar: "تعلم الآلة", en: "Machine Learning", descAr: "Machine Learning", descEn: "Machine learning" },
          { ar: "الذكاء الاصطناعي", en: "AI Development", descAr: "AI Development", descEn: "AI development" },
          { ar: "Business Intelligence", en: "Business Intelligence", descAr: "ذكاء الأعمال", descEn: "Business intelligence" },
          { ar: "Data Visualization", en: "Data Visualization", descAr: "تصور البيانات", descEn: "Data visualization" },
          { ar: "Big Data", en: "Big Data", descAr: "البيانات الضخمة", descEn: "Big data" },
          { ar: "Data Mining", en: "Data Mining", descAr: "التنقيب عن البيانات", descEn: "Data mining" },
          { ar: "Predictive Analytics", en: "Predictive Analytics", descAr: "التحليلات التنبؤية", descEn: "Predictive analytics" },
          { ar: "Statistical Analysis", en: "Statistical Analysis", descAr: "التحليل الإحصائي", descEn: "Statistical analysis" },
        ],
      },
      {
        ar: "خدمات الأمن السيبراني", en: "Cybersecurity Services", icon: "🔒",
        children: [
          { ar: "اختبار الاختراق", en: "Penetration Testing", descAr: "Penetration Testing", descEn: "Penetration testing" },
          { ar: "تقييم الثغرات", en: "Vulnerability Assessment", descAr: "Vulnerability Assessment", descEn: "Vulnerability assessment" },
          { ar: "استشارات الأمن", en: "Security Consulting", descAr: "Security Consulting", descEn: "Security consulting" },
          { ar: "Incident Response", en: "Incident Response", descAr: "الاستجابة للحوادث", descEn: "Incident response" },
          { ar: "Security Audits", en: "Security Audits", descAr: "مراجعة الأمن", descEn: "Security review" },
          { ar: "Compliance", en: "Compliance", descAr: "الامتثال", descEn: "Compliance" },
          { ar: "Security Training", en: "Security Training", descAr: "تدريب الأمن", descEn: "Security training" },
          { ar: "Forensics", en: "Digital Forensics", descAr: "التحقيقات الرقمية", descEn: "Digital forensics" },
          { ar: "SOC Services", en: "SOC Services", descAr: "مركز عمليات الأمن", descEn: "Security operations center" },
          { ar: "Risk Assessment", en: "Risk Assessment", descAr: "تقييم المخاطر", descEn: "Risk assessment" },
        ],
      },
      {
        ar: "خدمات العمل الحر الأخرى", en: "Other Freelance Services", icon: "🛠️",
        children: [
          { ar: "إدارة المتاجر الإلكترونية", en: "E-commerce Management", descAr: "E-commerce Management", descEn: "E-commerce management" },
          { ar: "خدمة العملاء عن بعد", en: "Remote Customer Service", descAr: "Remote Customer Service", descEn: "Remote customer service" },
          { ar: "إدخال البيانات", en: "Data Entry", descAr: "Data Entry", descEn: "Data entry" },
          { ar: "البحث على الإنترنت", en: "Internet Research", descAr: "Internet Research", descEn: "Internet research" },
          { ar: "النسخ الطبي", en: "Medical Transcription", descAr: "Medical Transcription", descEn: "Medical transcription" },
          { ar: "المحاسبة عن بعد", en: "Remote Accounting", descAr: "Remote Accounting", descEn: "Remote accounting" },
          { ar: "إدارة حسابات التواصل", en: "Social Media Account Management", descAr: "Social Media Management", descEn: "Social media management" },
          { ar: "Community Management", en: "Community Management", descAr: "إدارة المجتمعات", descEn: "Community management" },
          { ar: "Content Moderation", en: "Content Moderation", descAr: "مراقبة المحتوى", descEn: "Content moderation" },
          { ar: "Online Reputation Management", en: "Online Reputation Management", descAr: "إدارة السمعة", descEn: "Reputation management" },
          { ar: "إدارة حسابات التداول اليومي", en: "Day Trading Account Management", descAr: "تداول الأسهم والعملات الرقمية", descEn: "Stocks and crypto trading" },
          { ar: "إدارة حسابات التسويق بالعمولة", en: "Affiliate Marketing Management", descAr: "Affiliate Marketing Management", descEn: "Affiliate marketing management" },
          { ar: "خدمات الربط بين الشركات والفريلانسرز", en: "Freelance Marketplace Brokering", descAr: "Freelance Marketplace Brokering", descEn: "Freelance marketplace brokering" },
        ],
      },
    ],
  },
  {
    ar: "خدمات الذكاء الاصطناعي والوكلاء والأتمتة", en: "AI, Agents & Automation Services", icon: "🤖",
    children: [
      {
        ar: "خدمات الذكاء الاصطناعي والوكلاء والأتمتة", en: "AI, Agents & Automation", icon: "🤖",
        children: [
          { ar: "تطوير Chatbots", en: "AI Chatbot Development", descAr: "AI Chatbot Development", descEn: "AI chatbot development" },
          { ar: "Virtual AI Assistants", en: "Virtual AI Assistants", descAr: "مساعدات ذكاء اصطناعي", descEn: "AI assistants" },
          { ar: "AI Content Generation", en: "AI Content Generation", descAr: "إنتاج محتوى بالذكاء الاصطناعي", descEn: "AI content production" },
          { ar: "AI Voice Services", en: "AI Voice Services", descAr: "خدمات صوتية بالذكاء الاصطناعي", descEn: "AI voice services" },
          { ar: "AI Image Generation", en: "AI Image Generation", descAr: "توليد صور بالذكاء الاصطناعي", descEn: "AI image generation" },
          { ar: "AI Video Generation", en: "AI Video Generation", descAr: "توليد فيديو بالذكاء الاصطناعي", descEn: "AI video generation" },
          { ar: "Process Automation", en: "Process Automation", descAr: "أتمتة العمليات", descEn: "Process automation" },
          { ar: "Workflow Automation", en: "Workflow Automation", descAr: "أتمتة سير العمل", descEn: "Workflow automation" },
          { ar: "RPA Services", en: "RPA Services", descAr: "Robotic Process Automation", descEn: "Robotic process automation" },
          { ar: "AI Training Services", en: "AI Model Training Services", descAr: "تدريب نماذج الذكاء الاصطناعي", descEn: "AI model training" },
          { ar: "AI Integration Services", en: "AI Integration Services", descAr: "دمج حلول الذكاء الاصطناعي", descEn: "AI solutions integration" },
          { ar: "No-code/Low-code Development", en: "No-code/Low-code Development", descAr: "تطوير بدون برمجة", descEn: "No-code development" },
        ],
      },
    ],
  },
  {
    ar: "الخدمات الحية والتفاعلية", en: "Live & Interactive Services", icon: "🎤",
    children: [
      {
        ar: "الفعاليات والورش الحية", en: "Live Events & Workshops", icon: "🎪",
        children: [
          { ar: "ورش العمل الحية", en: "Live Workshops", descAr: "Live Workshops", descEn: "Live workshops" },
          { ar: "الندوات الحية", en: "Live Webinars", descAr: "Live Webinars", descEn: "Live webinars" },
          { ar: "المؤتمرات الافتراضية", en: "Virtual Conferences", descAr: "Virtual Conferences", descEn: "Virtual conferences" },
          { ar: "الدورات الحية", en: "Live Courses", descAr: "Live Courses", descEn: "Live courses" },
          { ar: "جلسات Q&A", en: "Q&A Sessions", descAr: "سؤال وجواب", descEn: "Questions and answers" },
          { ar: "Masterclasses", en: "Masterclasses", descAr: "دروس متقدمة", descEn: "Advanced lessons" },
          { ar: "Panel Discussions", en: "Panel Discussions", descAr: "نقاشات جماعية", descEn: "Group discussions" },
          { ar: "Virtual Summits", en: "Virtual Summits", descAr: "قمم افتراضية", descEn: "Virtual summits" },
          { ar: "Networking Events", en: "Networking Events", descAr: "فعاليات التواصل", descEn: "Networking events" },
          { ar: "Virtual Trade Shows", en: "Virtual Trade Shows", descAr: "معارض افتراضية", descEn: "Virtual exhibitions" },
        ],
      },
      {
        ar: "الاستشارات الشخصية", en: "Personal Consulting", icon: "🧑‍💼",
        children: [
          { ar: "استشارات 1-on-1", en: "1-on-1 Consulting", descAr: "جلسات فردية", descEn: "Individual sessions" },
          { ar: "Group Coaching", en: "Group Coaching", descAr: "تدريب جماعي", descEn: "Group coaching" },
          { ar: "Mentoring", en: "Mentoring", descAr: "الإرشاد", descEn: "Mentoring" },
          { ar: "Strategy Sessions", en: "Strategy Sessions", descAr: "جلسات استراتيجية", descEn: "Strategy sessions" },
          { ar: "Brainstorming Sessions", en: "Brainstorming Sessions", descAr: "جلسات عصف ذهني", descEn: "Brainstorming sessions" },
          { ar: "Review Sessions", en: "Review Sessions", descAr: "جلسات مراجعة", descEn: "Review sessions" },
          { ar: "Feedback Sessions", en: "Feedback Sessions", descAr: "جلسات تقييم", descEn: "Feedback sessions" },
          { ar: "Planning Sessions", en: "Planning Sessions", descAr: "جلسات تخطيط", descEn: "Planning sessions" },
          { ar: "Accountability Coaching", en: "Accountability Coaching", descAr: "تدريب المساءلة", descEn: "Accountability coaching" },
          { ar: "Performance Coaching", en: "Performance Coaching", descAr: "تدريب الأداء", descEn: "Performance coaching" },
        ],
      },
    ],
  },
];

// ============================================================
// C — فرص العمل الحر الرقمي عن بعد
// المجالات الـ 13 نصاً من البرومبت؛ الفروع مصممة وفق نمط المنصات
// المستنسخة (Upwork + Mostaql + Bahr) كما أوكل البرومبت ذلك لنا.
// ============================================================
export const JOB_CATALOG: CatalogEntry[] = [
  {
    ar: "الذكاء الاصطناعي والوكلاء والأتمتة", en: "AI, Agents & Automation", icon: "🤖",
    children: [
      { ar: "تطوير وكلاء الذكاء الاصطناعي", en: "AI Agent Development", descAr: "بناء وكلاء ومساعدات ذكية", descEn: "Building intelligent agents and assistants" },
      { ar: "هندسة البرومبتات", en: "Prompt Engineering", descAr: "تصميم وتحسين الأوامر", descEn: "Designing and optimizing prompts" },
      { ar: "تدريب وضبط النماذج", en: "Model Training & Fine-tuning", descAr: "تدريب نماذج الذكاء الاصطناعي وضبطها", descEn: "Training and fine-tuning AI models" },
      { ar: "أتمتة العمليات وسير العمل", en: "Process & Workflow Automation", descAr: "RPA وأتمتة المهام", descEn: "RPA and task automation" },
      { ar: "تكامل حلول الذكاء الاصطناعي", en: "AI Solutions Integration", descAr: "دمج الذكاء الاصطناعي في الأنظمة", descEn: "Integrating AI into systems" },
      { ar: "تطوير Chatbots", en: "Chatbot Development", descAr: "روبوتات محادثة ذكية", descEn: "Intelligent chatbots" },
    ],
  },
  {
    ar: "البرمجة والتطوير وتكنولوجيا المعلومات والتقنية", en: "Programming, Development & IT", icon: "💻",
    children: [
      { ar: "تطوير مواقع الويب", en: "Web Development", descAr: "واجهات أمامية وخلفية ومواقع كاملة", descEn: "Frontend, backend and full websites" },
      { ar: "تطوير تطبيقات الجوال", en: "Mobile App Development", descAr: "iOS وAndroid وCross-Platform", descEn: "iOS, Android and cross-platform" },
      { ar: "تطوير البرمجيات وسطح المكتب", en: "Software & Desktop Development", descAr: "أنظمة وتطبيقات سطح المكتب", descEn: "Systems and desktop applications" },
      { ar: "قواعد البيانات", en: "Databases", descAr: "تصميم وإدارة قواعد البيانات", descEn: "Database design and administration" },
      { ar: "DevOps والبنية التحتية السحابية", en: "DevOps & Cloud Infrastructure", descAr: "نشر وتشغيل وسحابة", descEn: "Deployment, operations and cloud" },
      { ar: "الأمن السيبراني", en: "Cybersecurity", descAr: "حماية واختبار اختراق", descEn: "Security and penetration testing" },
      { ar: "اختبار وجودة البرمجيات", en: "Software Testing & QA", descAr: "اختبارات يدوية وآلية", descEn: "Manual and automated testing" },
      { ar: "دعم تقني وشبكات", en: "IT Support & Networks", descAr: "دعم فني وإدارة شبكات", descEn: "Technical support and network administration" },
    ],
  },
  {
    ar: "الأعمال والمشاريع والمهام والإدارة", en: "Business, Projects, Tasks & Management", icon: "💼",
    children: [
      { ar: "إدارة المشاريع", en: "Project Management", descAr: "تخطيط وتنفيذ ومتابعة المشاريع", descEn: "Planning, executing and tracking projects" },
      { ar: "إدارة المنتجات", en: "Product Management", descAr: "إدارة دورة حياة المنتج", descEn: "Product lifecycle management" },
      { ar: "تطوير الأعمال", en: "Business Development", descAr: "شراكات ونمو وفرص", descEn: "Partnerships, growth and opportunities" },
      { ar: "ريادة الأعمال والاستشارات", en: "Entrepreneurship & Consulting", descAr: "استشارات الشركات الناشئة والأعمال", descEn: "Startup and business consulting" },
      { ar: "تنفيذ المهام والأعمال عن بعد", en: "Remote Tasks & Assignments", descAr: "مهام وأعمال متنوعة عن بعد", descEn: "Various remote tasks and assignments" },
      { ar: "المساعدة الافتراضية", en: "Virtual Assistance", descAr: "مساعد افتراضي إداري", descEn: "Administrative virtual assistant" },
    ],
  },
  {
    ar: "المالية والاقتصاد والمحاسبة", en: "Finance, Economics & Accounting", icon: "💰",
    children: [
      { ar: "المحاسبة ومسك الدفاتر", en: "Accounting & Bookkeeping", descAr: "قيود ودفاتر وتقارير مالية", descEn: "Entries, books and financial reports" },
      { ar: "التحليل المالي", en: "Financial Analysis", descAr: "تحليل القوائم والنسب المالية", descEn: "Financial statements and ratio analysis" },
      { ar: "التخطيط المالي والميزانيات", en: "Financial Planning & Budgeting", descAr: "خطط مالية وموازنات", descEn: "Financial plans and budgets" },
      { ar: "الضرائب والزكاة", en: "Tax & Zakat", descAr: "إقرارات وامتثال ضريبي وزكوي", descEn: "Tax and Zakat filings and compliance" },
      { ar: "الاستشارات الاقتصادية", en: "Economic Consulting", descAr: "دراسات وتحليلات اقتصادية", descEn: "Economic studies and analysis" },
      { ar: "التدقيق والمراجعة", en: "Auditing", descAr: "تدقيق ومراجعة مالية", descEn: "Financial auditing and review" },
    ],
  },
  {
    ar: "المبيعات والتسويق", en: "Sales & Marketing", icon: "📈",
    children: [
      { ar: "التسويق الرقمي", en: "Digital Marketing", descAr: "حملات وإعلانات رقمية", descEn: "Digital campaigns and ads" },
      { ar: "تحسين محركات البحث SEO", en: "SEO", descAr: "تحسين الظهور في محركات البحث", descEn: "Search engine visibility optimization" },
      { ar: "إدارة السوشيال ميديا", en: "Social Media Management", descAr: "إدارة الحسابات والمحتوى", descEn: "Account and content management" },
      { ar: "المبيعات وإدارة الحسابات", en: "Sales & Account Management", descAr: "بيع وتطوير علاقات العملاء", descEn: "Selling and customer relations" },
      { ar: "التسويق بالبريد الإلكتروني", en: "Email Marketing", descAr: "حملات بريدية ونشرات", descEn: "Email campaigns and newsletters" },
      { ar: "أبحاث التسويق", en: "Marketing Research", descAr: "دراسة الأسواق والمنافسين", descEn: "Market and competitor research" },
    ],
  },
  {
    ar: "الكتابة والترجمة والمحتوى", en: "Writing, Translation & Content", icon: "✍️",
    children: [
      { ar: "كتابة المحتوى والمقالات", en: "Content & Article Writing", descAr: "مقالات ومحتوى متخصص", descEn: "Articles and specialized content" },
      { ar: "الكتابة الإبداعية", en: "Creative Writing", descAr: "قصص وسيناريوهات ونصوص إبداعية", descEn: "Stories, scripts and creative texts" },
      { ar: "الكتابة التسويقية Copywriting", en: "Copywriting", descAr: "نصوص بيعية وإعلانية", descEn: "Sales and advertising copy" },
      { ar: "الترجمة", en: "Translation", descAr: "ترجمة عامة ومتخصصة", descEn: "General and specialized translation" },
      { ar: "التحرير والتدقيق اللغوي", en: "Editing & Proofreading", descAr: "تحرير وتدقيق النصوص", descEn: "Text editing and proofreading" },
      { ar: "التفريغ الصوتي", en: "Transcription", descAr: "تفريغ المقاطع الصوتية والمرئية", descEn: "Audio and video transcription" },
    ],
  },
  {
    ar: "التصميم والإبداع", en: "Design & Creativity", icon: "🎨",
    children: [
      { ar: "التصميم الجرافيكي", en: "Graphic Design", descAr: "شعارات وهويات ومطبوعات", descEn: "Logos, identities and prints" },
      { ar: "تصميم واجهات وتجربة المستخدم UI/UX", en: "UI/UX Design", descAr: "واجهات وتجربة استخدام", descEn: "Interfaces and user experience" },
      { ar: "الموشن جرافيك والأنيميشن", en: "Motion Graphics & Animation", descAr: "رسوم متحركة وموشن", descEn: "Animation and motion graphics" },
      { ar: "المونتاج والفيديو", en: "Video Editing", descAr: "مونتاج ومعالجة فيديو", descEn: "Video editing and processing" },
      { ar: "التصوير الفوتوغرافي", en: "Photography", descAr: "تصوير ومعالجة صور", descEn: "Photography and photo processing" },
      { ar: "التصميم ثلاثي الأبعاد", en: "3D Design", descAr: "نمذجة وتصميم 3D", descEn: "3D modeling and design" },
      { ar: "التصميم الصوتي والموسيقى", en: "Audio Design & Music", descAr: "تعليق صوتي وموسيقى ومؤثرات", descEn: "Voice over, music and sound effects" },
    ],
  },
  {
    ar: "إعداد الدراسات والبحوث والتقارير والخطط", en: "Studies, Research, Reports & Plans", icon: "🔬",
    children: [
      { ar: "دراسات الجدوى", en: "Feasibility Studies", descAr: "دراسات جدوى المشاريع", descEn: "Project feasibility studies" },
      { ar: "البحوث الأكاديمية والعلمية", en: "Academic & Scientific Research", descAr: "بحوث ودراسات علمية", descEn: "Scientific research and studies" },
      { ar: "أبحاث السوق", en: "Market Research", descAr: "دراسات السوق والمنافسين", descEn: "Market and competitor studies" },
      { ar: "خطط الأعمال", en: "Business Plans", descAr: "إعداد خطط الأعمال", descEn: "Business plan preparation" },
      { ar: "التقارير والتحليلات", en: "Reports & Analysis", descAr: "تقارير مهنية وتحليلات", descEn: "Professional reports and analysis" },
      { ar: "العروض التقديمية", en: "Presentations", descAr: "إعداد عروض احترافية", descEn: "Professional presentation preparation" },
    ],
  },
  {
    ar: "التعليم والتدريب", en: "Education & Training", icon: "🎓",
    children: [
      { ar: "التدريس الخصوصي", en: "Private Tutoring", descAr: "دروس خصوصية عن بعد", descEn: "Remote private lessons" },
      { ar: "تعليم اللغات", en: "Language Teaching", descAr: "تدريس اللغات", descEn: "Language instruction" },
      { ar: "إعداد المناهج والمواد التدريبية", en: "Curriculum & Training Material Development", descAr: "تصميم مناهج ومواد", descEn: "Curriculum and material design" },
      { ar: "التدريب المهني والمؤسسي", en: "Professional & Corporate Training", descAr: "تدريب موظفين وفرق", descEn: "Employee and team training" },
      { ar: "الكوتشينج والإرشاد", en: "Coaching & Mentoring", descAr: "توجيه مهني وشخصي", descEn: "Professional and personal guidance" },
    ],
  },
  {
    ar: "القانون", en: "Law", icon: "⚖️",
    children: [
      { ar: "الاستشارات القانونية", en: "Legal Consulting", descAr: "استشارات وآراء قانونية", descEn: "Legal consultations and opinions" },
      { ar: "صياغة العقود", en: "Contract Drafting", descAr: "إعداد وصياغة العقود", descEn: "Contract preparation and drafting" },
      { ar: "السياسات والامتثال", en: "Policies & Compliance", descAr: "سياسات ولوائح وامتثال", descEn: "Policies, regulations and compliance" },
      { ar: "الملكية الفكرية", en: "Intellectual Property", descAr: "علامات وحقوق ملكية", descEn: "Trademarks and IP rights" },
      { ar: "البحث القانوني", en: "Legal Research", descAr: "بحوث ودراسات قانونية", descEn: "Legal research and studies" },
    ],
  },
  {
    ar: "الهندسة والعمارة", en: "Engineering & Architecture", icon: "🏗️",
    children: [
      { ar: "التصميم المعماري", en: "Architectural Design", descAr: "تصاميم معمارية ومخططات", descEn: "Architectural designs and plans" },
      { ar: "التصميم الداخلي والديكور", en: "Interior Design & Decor", descAr: "تصميم داخلي وديكورات", descEn: "Interior design and decoration" },
      { ar: "الهندسة المدنية والإنشائية", en: "Civil & Structural Engineering", descAr: "تصاميم وحسابات إنشائية", descEn: "Structural designs and calculations" },
      { ar: "الهندسة الكهربائية والميكانيكية", en: "Electrical & Mechanical Engineering", descAr: "أنظمة كهربائية وميكانيكية", descEn: "Electrical and mechanical systems" },
      { ar: "الرسم الهندسي والنمذجة", en: "Engineering Drawing & Modeling", descAr: "AutoCAD وBIM ونمذجة", descEn: "AutoCAD, BIM and modeling" },
    ],
  },
  {
    ar: "الإدارة والدعم والتشغيل", en: "Administration, Support & Operations", icon: "🗂️",
    children: [
      { ar: "الدعم الإداري", en: "Administrative Support", descAr: "أعمال إدارية ومكتبية عن بعد", descEn: "Remote administrative and office work" },
      { ar: "إدخال ومعالجة البيانات", en: "Data Entry & Processing", descAr: "إدخال بيانات وتنظيمها", descEn: "Data entry and organization" },
      { ar: "خدمة العملاء", en: "Customer Service", descAr: "دعم عملاء عن بعد", descEn: "Remote customer support" },
      { ar: "إدارة المتاجر والمنصات", en: "Store & Platform Management", descAr: "تشغيل متاجر ومنصات إلكترونية", descEn: "Operating stores and online platforms" },
      { ar: "إدارة المجتمعات والمحتوى", en: "Community & Content Management", descAr: "إدارة مجتمعات ومراقبة محتوى", descEn: "Community management and content moderation" },
    ],
  },
  {
    ar: "الموارد البشرية والتوظيف", en: "Human Resources & Recruitment", icon: "👥",
    children: [
      { ar: "التوظيف واستقطاب المواهب", en: "Recruitment & Talent Acquisition", descAr: "بحث واستقطاب الكفاءات", descEn: "Talent search and acquisition" },
      { ar: "إدارة الموارد البشرية", en: "HR Management", descAr: "سياسات وإجراءات وشؤون موظفين", descEn: "Policies, procedures and personnel affairs" },
      { ar: "الرواتب والمزايا", en: "Payroll & Benefits", descAr: "إعداد رواتب ومزايا", descEn: "Payroll and benefits processing" },
      { ar: "تقييم الأداء", en: "Performance Evaluation", descAr: "أنظمة تقييم الأداء", descEn: "Performance evaluation systems" },
      { ar: "تطوير المواهب والتدريب", en: "Talent Development & Training", descAr: "خطط تطوير الموظفين", descEn: "Employee development plans" },
    ],
  },
];
